- .eslintignore
- .eslintrc
- .gitignore
- LICENSE
- index.ts
- jest.config.js
- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
Initial Typescript setup with eslint and jest testing.
> chore: Initial project setup

- jest.config.js
- src/models/CommonModel.ts
- src/models/CommonSchema.ts
- src/models/Schema.ts
- test/models/CommonModel.spec.ts
- test/models/Schema.spec.ts
Added basic common model and schema together with unit tests as described in https://github.com/asyncapi/shape-up-process/issues/51.
Tests are more or less the same from https://github.com/asyncapi/parser-js/blob/master/test/models/schema_test.js
> chore: Added basic common model and schema with test

- .eslintrc
- package-lock.json
- package.json
- src/interfaces/I_InputProcessor.ts
- src/models/AbstractInputProcessor.ts
- src/models/CommonInputModel.ts
- src/processors/JsonSchemaInputProcessor.ts
- test/processors/JsonSchemaInputProcessor.spec.ts
- test/processors/JsonSchemaInputProcessor/absence_type.json
- test/processors/JsonSchemaInputProcessor/applying_conditional_schemas.json
- test/processors/JsonSchemaInputProcessor/combination_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/absence_type.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/applying_conditional_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/combination_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/enum.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/items.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/multiple_objects.json
- test/processors/JsonSchemaInputProcessor/enum.json
- test/processors/JsonSchemaInputProcessor/items.json
- test/processors/JsonSchemaInputProcessor/multiple_objects.json
This PR adds the input processor for JSON Schema together with integration tests.
> chore: Added JSON Schema input processor and tests

- package-lock.json
- src/models/OutputModel.ts
- src/models/index.ts
- test/models/OutputModel.spec.ts
As in title: chore: add output model shape and related tests
See also https://github.com/asyncapi/shape-up-process/issues/52
> chore: add output model shape and related tests

- src/models/CommonModel.ts
- src/models/CommonSchema.ts
- src/models/Schema.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/basic.json
- test/processors/AsyncAPIInputProcessor/commonInputModel/basic.json
Added AsyncAPI input processor for AsyncAPI together with tests.
blocked by #3
> chore: Added input processor for AsyncAPI with tests

- src/InputProcessor.ts
- test/InputProcessor.spec.ts
This PR adds the main input processor together with integration tests
Blocked by #4 and #3
> chore: Added main input processor together with tests

- .eslintrc
- API.md
- package.json
- src/InputProcessor.ts
- src/generators/AbstractGenerator.ts
- src/generators/index.ts
- src/generators/java/JavaGenerator.ts
- src/generators/java/index.ts
- src/generators/javascript/TypeScriptGenerator.ts
- src/generators/javascript/index.ts
- src/models/AbstractInputProcessor.ts
- src/models/CommonInputModel.ts
- src/models/OutputModel.ts
- src/models/index.ts
- src/processors/AbstractInputProcessor.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/InputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/index.ts
- test/InputProcessor.spec.ts
- test/generators/AbstractGenerator.spec.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/javascript/TypeScriptGenerator.spec.ts
- test/models/OutputModel.spec.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/JsonSchemaInputProcessor.spec.ts
As in title: make signatures for generators. At the moment only for Java and TypeScript. In future, every language will follow in this same convention.
See also https://github.com/asyncapi/shape-up-process/issues/53
> chore: add signatures for generators

- README.md
Fixes missing statement in readme
> docs: added missing description for simplification

- src/generators/typescript/renderers/ClassRenderer.ts
- src/generators/typescript/renderers/EnumRenderer.ts
- src/generators/typescript/renderers/InterfaceRenderer.ts
- src/generators/typescript/renderers/TypeRenderer.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
Render in proper way properties in TS class:
- add `_` prefix for private fields in class.
- render appropriate object shape for constructor argument.
> fix: render TS class properties in proper way

- test/generators/AbstractGenerator.spec.ts
- test/generators/AbstractRenderer.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/helpers/FormatHelpers.spec.ts
- test/simplification/enum.spec.ts
- test/simplification/items.spec.ts
- test/simplification/name.spec.ts
- test/simplification/properties.spec.ts
- test/simplification/required.spec.ts
- test/simplification/types.spec.ts
This PR improves upon our branch test coverage.
> chore: improved branch test coverage

- src/generators/typescript/TypeScriptRenderer.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
This PR ensures the type for properties are rendered with enums if sat.
solves https://github.com/asyncapi/generator-model-sdk/issues/133
> feat: ensure unions of enums are rendered for properties for TS

- src/index.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/utils/LoggingInterface.ts
- src/utils/index.ts
- test/utils/LoggingInterface.spec.ts
This PR adds a logging interface to the library to allow logging for different scenarios.
fixes #152
> feat: add a logging interface

- sonar-project.properties
This PR adds a sonarcloud configuration file to ignore duplicates lines for renderers.
> ci: added sonar cloud config to ignore duplicate code

- .all-contributorsrc
- README.md
- docs/input_processing.md
- docs/logging.md
- docs/presets.md
- package-lock.json
- package.json
This PR changes the name of the repository.
fixes https://github.com/asyncapi/modelina/issues/132
> feat: rename library to modelina

- src/generators/java/JavaGenerator.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/generators/javascript/JavaScriptGenerator.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/generators/typescript/renderers/TypeRenderer.ts
- src/processors/JsonSchemaInputProcessor.ts
This commit replaces `switch` statements with `if else` since there are very small `switch` statements at some places which have only 1 case.
Signed-off-by: Kanwal Singh <kanwal.88singh@gmail.com>
Fixes #236
> refactor: replace `switch` statements with `if else`.

- src/generators/java/JavaRenderer.ts
This PR fixes/resolves 3 code smells from `JavaRenderer.ts`. 
Signed-off-by: Kanwal Singh <kanwal.88singh@gmail.com>
Fixes #235
> refactor: remove code smells from `JavaRenderer`

- docs/interpretation_of_JSON_Schema_draft_7.md
- src/interpreter/InterpretDependencies.ts
- src/interpreter/Interpreter.ts
- test/interpreter/unit/Intepreter.spec.ts
- test/interpreter/unit/InterpretDependencies.spec.ts
This PR makes sure schema dependencies are iterated and merged together.
fixes #79
> feat: interpret dependencies

- docs/presets.md
- test/models/CommonModel.spec.ts
This PR removes any references to Schema from CommonModel test
> test: removed Schema from CommonModel test

- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
This PR renders the pattern properties for the java class.
Related to #154
> feat: render pattern properties for Java class

- README.md
Remove duplicated property `state` in the example located in `README.md` file.
> docs: remove duplicated state property in the example

- README.md
This PR fixes the example in `README.md` by:
- Encapsulate call to the generator in an async func.
- Add `console.log` for all the generated models.
- Show the real output of the example.
> docs: fix example in README.md. Encapsulate in async + other fixes

- docs/generators.md
> docs: fixed generator C# table

- src/generators/csharp/renderers/EnumRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
This PR adds an extension to enums, which allows the retrieval of the associated enum values.
fixes https://github.com/asyncapi/modelina/issues/336
> feat: csharp enum rendering associated values

- LICENSE
This fixes the license file according to https://github.com/asyncapi/spec/blob/master/LICENSE
> fix: license update

- README.md
- examples/asyncapi-from-object/index.ts
- examples/asyncapi-from-parser/index.ts
- test/blackbox/blackbox.spec.ts
- test/blackbox/docs/AsyncAPI-2_2/dummy.json
This PR adds some missing docs and tests for AsyncAPI 2.2 support
> chore: add missing docs and tests for AsyncAPI 2.2 release

- src/generators/java/JavaGenerator.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
Last PR I just used simple pascal case conversion, when it should use the given naming format.
> fix: java generateCompleteModels do not use naming format

- CODEOWNERS
This PR introduce the CODEOWNER file.
Fixes: https://github.com/asyncapi/modelina/issues/508
> docs: add code owners

- docs/usage.md
- examples/README.md
- examples/generate-java-models/README.md
- examples/generate-java-models/__snapshots__/index.spec.ts.snap
- examples/generate-java-models/index.spec.ts
- examples/generate-java-models/index.ts
- examples/generate-java-models/package-lock.json
- examples/generate-java-models/package.json
Description
Created example to show how to generate Java data models in 
https://github.com/mahakporwal02/modelina/tree/issue/409/examples/generate-java-models.
Updated documentation in 
https://github.com/mahakporwal02/modelina/blob/issue/409/examples/generate-java-models/README.md
https://github.com/mahakporwal02/modelina/blob/issue/409/examples/README.md
https://github.com/mahakporwal02/modelina/blob/issue/409/docs/usage.md
Performed the implementation for the example.
Updated snapshot for test.
Tests are passing :)
Related issue(s)
Resolves #409.
> docs: generate java data models

- src/models/CommonModel.ts
- test/models/CommonModel.spec.ts
This PR addresses some model dependencies that are not accurately resolved.
Fixes https://github.com/asyncapi/modelina/issues/542
> fix: model dependencies are not accurately resolved

- README.md
- docs/usage.md
- examples/openapi-from-object/README.md
- examples/openapi-from-object/__snapshots__/index.spec.ts.snap
- examples/openapi-from-object/index.spec.ts
- examples/openapi-from-object/index.ts
- examples/openapi-from-object/package-lock.json
- examples/openapi-from-object/package.json
This PR adds OpenAPI input as an example.
> docs: add OpenAPI input as example

- docs/advanced.md
- docs/languages/JavaScript.md
- examples/README.md
- examples/javascript-use-cjs/README.md
- examples/javascript-use-cjs/__snapshots__/index.spec.ts.snap
- examples/javascript-use-cjs/index.spec.ts
- examples/javascript-use-cjs/index.ts
- examples/javascript-use-cjs/package-lock.json
- examples/javascript-use-cjs/package.json
- examples/javascript-use-esm/README.md
- examples/javascript-use-esm/__snapshots__/index.spec.ts.snap
- examples/javascript-use-esm/index.spec.ts
- examples/javascript-use-esm/index.ts
- examples/javascript-use-esm/package-lock.json
- examples/javascript-use-esm/package.json
- package.json
- src/generators/javascript/JavaScriptFileGenerator.ts
- src/generators/javascript/JavaScriptGenerator.ts
- src/generators/javascript/index.ts
- test/generators/javascript/JavaScriptFileGenerator.spec.ts
- test/generators/javascript/JavaScriptGenerator.spec.ts
- test/generators/javascript/__snapshots__/JavaScriptGenerator.spec.ts.snap
This PR adds both complete and file output for the JS generator.
Fixes https://github.com/asyncapi/modelina/issues/400
> feat: complete model rendering and file output for JavaScript generator

- docs/advanced.md
- docs/languages/TypeScript.md
- examples/README.md
- examples/javascript-use-esm/__snapshots__/index.spec.ts.snap
- examples/javascript-use-esm/package.json
- examples/typescript-use-cjs/README.md
- examples/typescript-use-cjs/__snapshots__/index.spec.ts.snap
- examples/typescript-use-cjs/index.spec.ts
- examples/typescript-use-cjs/index.ts
- examples/typescript-use-cjs/package-lock.json
- examples/typescript-use-cjs/package.json
- examples/typescript-use-esm/README.md
- examples/typescript-use-esm/__snapshots__/index.spec.ts.snap
- examples/typescript-use-esm/index.spec.ts
- examples/typescript-use-esm/index.ts
- examples/typescript-use-esm/package-lock.json
- examples/typescript-use-esm/package.json
- src/generators/javascript/JavaScriptFileGenerator.ts
- src/generators/javascript/JavaScriptGenerator.ts
- src/generators/typescript/TypeScriptFileGenerator.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/generators/typescript/index.ts
- src/models/CommonModel.ts
- test/blackbox/blackbox.spec.ts
- test/generators/javascript/JavaScriptFileGenerator.spec.ts
- test/generators/javascript/__snapshots__/JavaScriptGenerator.spec.ts.snap
- test/generators/typescript/TypeScriptFileGenerator.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/models/CommonModel.spec.ts
This PR adds file output for the TypeScript generator.
Fixes #399
> feat: add file output for TypeScript generator

- docs/advanced.md
- examples/README.md
- examples/include-custom-function/README.md
- examples/include-custom-function/__snapshots__/index.spec.ts.snap
- examples/include-custom-function/index.spec.ts
- examples/include-custom-function/index.ts
- examples/include-custom-function/package-lock.json
- examples/include-custom-function/package.json
Added example on how to include custom function in data model.
https://github.com/mahakporwal02/modelina/tree/issue-413/examples/include-custom-function
Updated documentation.
https://github.com/mahakporwal02/modelina/blob/issue-413/examples/include-custom-function/README.md
https://github.com/mahakporwal02/modelina/blob/issue-413/examples/README.md
https://github.com/mahakporwal02/modelina/blob/issue-413/docs/advanced.md
#413
> docs: example on how to include a custom function in the data model

- docs/usage.md
Linked advance usage of language to usage.md
Fixes #587
> docs: linked to advance language usage

- docs/languages/Java.md
- examples/java-generate-jackson-annotation/README.md
- examples/java-generate-jackson-annotation/__snapshots__/index.spec.ts.snap
- examples/java-generate-jackson-annotation/index.spec.ts
- examples/java-generate-jackson-annotation/index.ts
- examples/java-generate-jackson-annotation/package-lock.json
- examples/java-generate-jackson-annotation/package.json
-  Added `examples/java-generate-jackson-annotation/`
- Modified `docs/languages/Java.md`
Fixes #427
> docs: added jackson annotation example

- docs/languages/Csharp.md
- Updated `docs/language/Csharp.md`
Fixes #446
> docs: added dependency info in csharp

- examples/README.md
- Added java un/marshalling reference to `examples/README.md`
> docs: add java un/marshalling reference to docs

- .all-contributorsrc
- CODEOWNERS
- README.md
This PR invites @Samridhi-98 to become a language champion for the TS and JS generators.
@derberg @fmvilas we need you to add @Samridhi-98 to get write access to the repo.
> docs: add Samridhi-98 as language champion for TS and JS

- docs/generators.md
-  Modified `generator.md`
Fixes #483
> docs: broken customization links

- src/generators/javascript/JavaScriptPreset.ts
- src/generators/javascript/presets/CommonPreset.ts
- src/generators/typescript/presets/CommonPreset.ts
-  Modified `javascriptpresets` , `commonpresets`
Fixes #708
> fix: presets options to generic in javascript

- src/generators/java/JavaPreset.ts
- src/generators/java/presets/CommonPreset.ts
-  Modified `javapreset` and `commonpreset`
Fixes #711
> fix: presets options to generic in java

- src/generators/go/GoPreset.ts
-  Modified `GoPreset.ts`
Fixes #710
> fix: presets options to generic in go

- src/generators/csharp/CSharpPreset.ts
- src/generators/csharp/presets/CommonPreset.ts
- Modified `CsharpPreset` & `CommonPreset`
Fixes #707
> fix: presets options to generic in csharp

- src/generators/csharp/CSharpConstrainer.ts
- src/generators/csharp/CSharpGenerator.ts
- src/generators/csharp/constrainer/EnumConstrainer.ts
- src/generators/csharp/constrainer/ModelNameConstrainer.ts
- src/generators/csharp/constrainer/PropertyKeyConstrainer.ts
- src/generators/java/JavaGenerator.ts
- test/TestUtils/TestRenderers.ts
- test/generators/csharp/CSharpConstrainer.spec.ts
- test/generators/csharp/constrainer/EnumConstrainer.spec.ts
- test/generators/csharp/constrainer/ModelNameConstrainer.spec.ts
- test/generators/csharp/constrainer/PropertyKeyConstrainer.spec.ts
This PR converts the CSharp generator to the new constraint setup introduced in https://github.com/asyncapi/modelina/pull/725
> refactor: convert CSharp to new constraint setup

- src/generators/javascript/JavaScriptConstrainer.ts
- src/generators/javascript/JavaScriptGenerator.ts
- src/generators/javascript/constrainer/EnumConstrainer.ts
- src/generators/javascript/constrainer/ModelNameConstrainer.ts
- src/generators/javascript/constrainer/PropertyKeyConstrainer.ts
- test/TestUtils/TestRenderers.ts
- test/generators/javascript/JavaScriptConstrainer.spec.ts
- test/generators/javascript/constrainer/EnumConstrainer.spec.ts
- test/generators/javascript/constrainer/ModelNameConstrainer.spec.ts
- test/generators/javascript/constrainer/PropertyKeyConstrainer.spec.ts
This PR converts the TS generator to the new constraint setup introduced in https://github.com/asyncapi/modelina/pull/725
> refactor: convert JS to new constraint setup

- CODEOWNERS
- docs/champions.md
This PR adds a few changes to the champions document as well as updates the code owners file to reflect the new generator and inputs.
@ron-debajyoti did you want to champion the TS input?
> docs: add more details to champions document

- docs/languages/Csharp.md
- examples/README.md
- examples/csharp-use-inheritance/README.md
- examples/csharp-use-inheritance/__snapshots__/index.spec.ts.snap
- examples/csharp-use-inheritance/index.spec.ts
- examples/csharp-use-inheritance/index.ts
- examples/csharp-use-inheritance/package-lock.json
- examples/csharp-use-inheritance/package.json
This PR adds an inheritance example, where we overwrite the entire rendering process.
Related to https://stackoverflow.com/questions/72638195/modelina-csharp-generator-add-inheritance
> docs: add inheritance example

- src/generators/csharp/CSharpFileGenerator.ts
- src/generators/csharp/CSharpGenerator.ts
- src/generators/csharp/renderers/ClassRenderer.ts
- src/generators/dart/DartGenerator.ts
- src/generators/dart/DartRenderer.ts
- src/generators/java/JavaGenerator.ts
- src/generators/java/renderers/ClassRenderer.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/helpers/NameHelpers.ts
- src/models/ConstrainedMetaModel.ts
This PR fixes all remaining build errors.
> chore: fix build errors

- src/helpers/Constraints.ts
- test/helpers/Constraints.spec.ts
This PR fixes the constrain functions and adds tests
> chore: add test and fix constrain implementation

- src/generators/java/presets/ConstraintsPreset.ts
This PR fixes a wrongful import
> chore: fix wrongful import 

- src/generators/dart/DartRenderer.ts
- Fixes import path of helpers in DartRenderer
> fix: import path of helpers in DartRenderer

- src/helpers/CommonModelToMetaModel.ts
- test/helpers/CommonModelToMetaModel.spec.ts
This PR makes sure we convert a common model which has all possible types to be converted to any model.
> chore: convert to any model from common model

- test/models/OutputModel.spec.ts
This PR fixes the tests for OutputModel
> chore: fix tests for OutputModel

- src/helpers/CommonModelToMetaModel.ts
- test/helpers/CommonModelToMetaModel.spec.ts
This PR fixes enum models are not created properly from CommonModel by moving all the primitive meta models to be converted last.
> chore: fix enum model conversion

- src/helpers/ConstrainHelpers.ts
- src/models/ConstrainedMetaModel.ts
- test/helpers/ConstrainHelpers.spec.ts
- test/helpers/Constraints.spec.ts
As left over from https://github.com/asyncapi/modelina/pull/799 I removed the unused argument and fixed some general tests
> chore: removed unused property and fix general tests

- package.json
This PR force triggers a new release for Modelina and the next branch, as it seems the last chore release did not work.
> feat: force trigger release

- package.json
This PR like the other two #831 and  #832 tries to trigger a release for `1.0.0-next.1`.
> feat: force release

- package.json
Trigger version 1 pre-release for `next` branch.
> feat!: trigger initial version 1

- README.md
This PR makes notice about the next branch so going forward any features should be targeting it.
> docs: make notice about next branch

- src/helpers/TypeHelpers.ts
- test/helpers/TypeHelpers.spec.ts
This PR removes some unused functions.
> chore: remove unused functions

- README.md
This removes a duplicate entry of dart.
> docs: remove duplicate dart output

- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
Because of the latest PR was not updated with the newest in `next` we ended with incorrect snapshots which is now blocking release.
> test: update snapshot for failing test

- docs/usage.md
- examples/README.md
- examples/json-schema-draft4-from-object/README.md
- examples/json-schema-draft4-from-object/__snapshots__/index.spec.ts.snap
- examples/json-schema-draft4-from-object/index.spec.ts
- examples/json-schema-draft4-from-object/index.ts
- examples/json-schema-draft4-from-object/package-lock.json
- examples/json-schema-draft4-from-object/package.json
- src/generators/typescript/TypeScriptRenderer.ts
- Added new example for json-schema-draft4-from-object as mentioned in #852 
Fixes #852
> chore: add new example for json-schema-draft4-from-object (#852)

- docs/usage.md
- examples/README.md
- examples/json-schema-draft6-from-object/README.md
- examples/json-schema-draft6-from-object/__snapshots__/index.spec.ts.snap
- examples/json-schema-draft6-from-object/index.spec.ts
- examples/json-schema-draft6-from-object/index.ts
- examples/json-schema-draft6-from-object/package-lock.json
- examples/json-schema-draft6-from-object/package.json
- Adds new schema models for draft 6
Fixes #853
> chore: add a new example for JSON schema darft 6

- jest.config.js
- package-lock.json
- package.json
Use `@swc/jest` to speedup tests.
`test:library`:
- current `ts-jest` preset: 64.586s
- `@swc/jest`: 36.319s
`test:examples`:
- current `ts-jest` preset: 48.714s
- `@swc/jest`: 27.995s
> ci: use @swc/jest to speedup tests

- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
While merging two PRs the test snapshots where not correctly updated.
> ci: fix broken release pipeline

- docs/languages/Python.md
- docs/presets.md
- examples/README.md
- examples/generate-python-pydantic-models/README.md
- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-pydantic-models/index.spec.ts
- examples/generate-python-pydantic-models/index.ts
- examples/generate-python-pydantic-models/package-lock.json
- examples/generate-python-pydantic-models/package.json
- src/generators/python/index.ts
- src/generators/python/presets/Pydantic.ts
- src/generators/python/presets/index.ts
- Classes are inherited from `BaseModel`
- Fields are annotated
Resolves #963
> feat: add basic pydantic support for python models

- docs/languages/Python.md
- package.json
For the past two merges, a new version has not been triggered. It might be because they were merged using merge commit instead of squash.
> feat: trigger release

- docs/languages/Python.md
- examples/generate-python-complete-models/README.md
- examples/generate-python-complete-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-complete-models/index.spec.ts
- examples/generate-python-complete-models/index.ts
- examples/generate-python-complete-models/package-lock.json
- examples/generate-python-complete-models/package.json
- examples/generate-python-models/index.spec.ts
- examples/generate-python-models/index.ts
- src/generators/python/PythonGenerator.ts
- Adding a PythonOption to specify import style
See also #975
> fix: implicit python import error

- docs/contributing.md
This PR adds contribution guidelines for how to add presets and the requirements to do it.
Fixes https://github.com/asyncapi/modelina/issues/965
> docs: add contributing guidelines for presets

- examples/generate-java-models/__snapshots__/index.spec.ts.snap
- examples/generate-to-files/__snapshots__/index.spec.ts.snap
- examples/java-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/java-generate-equals/__snapshots__/index.spec.ts.snap
- examples/java-generate-hashcode/__snapshots__/index.spec.ts.snap
- examples/java-generate-marshalling/__snapshots__/index.spec.ts.snap
- examples/java-generate-tostring/__snapshots__/index.spec.ts.snap
- src/generators/java/JavaRenderer.ts
- test/generators/java/JavaRenderer.spec.ts
- Add type as a fallback if no special handling for format has been provided.
- Fixes #533 
> fix: use type as a fallback if no special handling for format is provided

- examples/csharp-overwrite-enum-naming/__snapshots__/index.spec.ts.snap
- src/generators/csharp/CSharpConstrainer.ts
- src/generators/csharp/renderers/EnumRenderer.ts
- test/generators/csharp/CSharpConstrainer.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
This PR adds more precise C# enum types in order to give the best possible signature for support functions.
Fixes https://github.com/asyncapi/modelina/issues/943
> feat: add precise csharp enum type

- package-lock.json
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
This fixes the release workflow.
> test: update snapshots

- docs/constraints.md
> docs: fix wrong link to constraint example

- .github/workflows/scripts/mailchimp/package-lock.json
- docs/advanced.md
- examples/integrate-with-react/package-lock.json
- examples/passing-interpreter-options/README.md
- examples/passing-interpreter-options/__snapshots__/index.spec.ts.snap
- examples/passing-interpreter-options/index.spec.ts
- examples/passing-interpreter-options/index.ts
- examples/passing-interpreter-options/package-lock.json
- examples/passing-interpreter-options/package.json
- package-lock.json
- package.json
- src/interpreter/InterpretAdditionalItems.ts
- src/interpreter/InterpretAdditionalProperties.ts
- src/interpreter/Interpreter.ts
This PR updates the next branch with the latest master changes.
> chore: update next with master

- README.md
This PR fixes the blackbox badge and includes the CLI usage example
> docs: improve readme 

- docs/languages/Csharp.md
This PR updates the dependency of C# 
Resolves #915
> docs: update c# dependency

- docs/migrations/version-1-to-2.md
- src/models/CommonModel.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/models/CommonModel.spec.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/operation_oneof.json
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
- adds union type when operation.message.oneOf is set
Resolves #1111
> fix!: adds union type when operation.message.oneOf is set

- .all-contributorsrc
- .github/workflows/add-good-first-issue-labels.yml
- README.md
- docs/advanced.md
- docs/languages/Csharp.md
- package-lock.json
- package.json
- src/interpreter/InterpretAdditionalItems.ts
- src/interpreter/InterpretAdditionalProperties.ts
- src/interpreter/Interpreter.ts
- src/models/ConstrainedMetaModel.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/blackbox/BlackBoxTestFiles.ts
- test/blackbox/README.md
- test/blackbox/docs/AsyncAPI-2_6/dummy.json
- test/interpreter/unit/InterpretAdditionalItems.spec.ts
- test/interpreter/unit/InterpretAdditionalProperties.spec.ts
- test/models/ConstrainedMetaModel.spec.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
This PR updates `next` branch with recent changes to `master`.
Must be merged with regular merge commit.
> feat: update next with master

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts
- modelina-website/src/pages/api/functions/CSharpGenerator.ts
- modelina-website/src/types/index.ts
- Added option in the playground to select collection type.
Resolves #1180
> chore(website): add option to modify array type for C# in playground

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts
- modelina-website/src/pages/api/functions/CSharpGenerator.ts
- modelina-website/src/types/index.ts
- Added a checkbox in playground to include auto-implemented properties in C#
Fixes #1179
> chore(website): add support for auto implement properties for C# in playground

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts
- modelina-website/src/pages/api/functions/TypeScriptGenerator.ts
- modelina-website/src/types/index.ts
- Added checkbox in playground to include descriptions.
fixes #1174
> chore(website): add support for including descriptions for Typescript in playground

- package-lock.json
It seems like the CI system is broken for some weird reason.... Pretty sure it has something to do with the package.lock file as it's currently using v3 which does not really work well with node 14...
- https://github.com/asyncapi/modelina/pull/1197
- https://github.com/asyncapi/modelina/pull/1196
This PR tries to fix that.....
> chore: fix package.lock problems

- src/generators/php/Constants.ts
- src/generators/php/PhpConstrainer.ts
- src/generators/php/PhpFileGenerator.ts
- src/generators/php/presets/DescriptionPreset.ts
- src/generators/php/renderers/ClassRenderer.ts
- src/generators/php/renderers/EnumRenderer.ts
- test/generators/php/PhpConstrainer.spec.ts
- test/generators/php/__snapshots__/PhpGenerator.spec.ts.snap
- test/generators/php/presets/DescriptionPreset.spec.ts
- test/generators/php/presets/__snapshots__/DescriptionPreset.spec.ts.snap
* Define PHP types
* Define Enum and Class present renderers
* Publish snapshots -> Not ideal, but seems to be looking decent
> feat: add correct PHP enum and class rendering

- package-lock.json
- src/generators/php/PhpConstrainer.ts
- src/generators/php/renderers/ClassRenderer.ts
- test/generators/php/PhpConstrainer.spec.ts
- test/generators/php/PhpGenerator.spec.ts
- test/generators/php/__snapshots__/PhpGenerator.spec.ts.snap
- test/generators/php/presets/__snapshots__/DescriptionPreset.spec.ts.snap
PHP does not have a dictionary or any other nice types. So the `mixed` should be applied. The nullable parameters are specified with `?` mark. ex. `?string`
> feat: php generator - nullable && mixed types

- README.md
Fixed the contributing link in readme
https://user-images.githubusercontent.com/91362589/230572730-c84c20d7-8090-4f85-9d0e-a1321204d243.mp4
<br>
Fixes #1224
> docs: fix the contributing link in readme

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts
- modelina-website/src/pages/api/functions/TypeScriptGenerator.ts
- modelina-website/src/types/index.ts
- Added option for generation of TypeScript using different module systems
- Added UI to support this operation in Playground
Resolves #1173
> chore(website): add TypeScript module system option for playground

- modelina-website/src/components/layouts/MobileNavMenu.tsx
Fixed the text and broken link on Mobile devices
Resolves #1228
> chore(website): fixed the text and broken link on Mobile devices

- modelina-website/package-lock.json
- modelina-website/package.json
Added cross-env package & changed dev script from 
`NODE_OPTIONS='--inspect' next dev` to `cross-env NODE_OPTIONS='--inspect' next dev`
Resolves #1230
> chore(website): add cross-env package & changed dev script

- modelina-website/src/components/layouts/MobileNavMenu.tsx
- modelina-website/src/components/layouts/NavBar.tsx
Remove duplicate link from navbar.
Fixes #1238
> chore(website): remove duplicate link from navbar

- src/models/ConstrainedMetaModel.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/helpers/ConstrainHelpers.spec.ts
- test/models/ConstrainedMetaModel.spec.ts
- this ensures that we don't get incorrect values for constants.
> fix!: should not carry over options from metaModel to constrainedModel

- src/generators/java/JavaPreset.ts
This PR fixes an absolute reference that the project don't like, which fails the black-box testing 😄
> fix: wrong import for Java preset

- package-lock.json
Revert changes from https://github.com/asyncapi/modelina/pull/1205/commits/f4dc26a1374170eb4d48c4d97b2a179309ff3b2c
> feat: php generator - revert package-lock.json changes

- docs/languages/Php.md
- examples/README.md
- examples/php-generate-documentation-preset/README.md
- examples/php-generate-documentation-preset/__snapshots__/index.spec.ts.snap
- examples/php-generate-documentation-preset/index.spec.ts
- examples/php-generate-documentation-preset/index.ts
- examples/php-generate-documentation-preset/package-lock.json
- examples/php-generate-documentation-preset/package.json
PS. Let me know if that was what we were missing :)
> feat: php generator - description preset example

- test/blackbox/BlackBoxTestFiles.ts
- test/blackbox/blackbox-csharp.spec.ts
- test/blackbox/blackbox-go.spec.ts
- test/blackbox/blackbox-java.spec.ts
- test/blackbox/blackbox-javascript.spec.ts
- test/blackbox/blackbox-kotlin.spec.ts
- test/blackbox/blackbox-python.spec.ts
- test/blackbox/blackbox-rust.spec.ts
- test/blackbox/blackbox-typescript.spec.ts
* fix spelling mistake in comment header
* improve java and kotlin test descriptions
> chore: blackbox tests

- CODEOWNERS
Let's try to maintain and expand PHP generator 😄
> chore: add ferror to PHP codeowners

- modelina-website/src/components/playground/Playground.tsx
- fixed the loader of playground section
fixes #1316
> chore(website): fixed the overlapping of playground loader

- modelina-website/src/components/examples/Examples.tsx
- Made sidebar responsive for the mobile view by making it collapsable
fixes #1315
> chore(website): add responsive sidebar to examples

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts
- modelina-website/src/pages/api/functions/CSharpGenerator.ts
- modelina-website/src/types/index.ts
- src/generators/csharp/CSharpGenerator.ts
- add System.Text.Json serialization support in the playground
- Fixes #1175
> chore(website): add System.Text.Json serialization support in the playground

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
- modelina-website/src/components/playground/options/CplusplusGeneratorOptions.tsx
- modelina-website/src/components/playground/options/PhpGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/CSharpGenerator.ts
- modelina-website/src/helpers/GeneratorCode/CplusplusGenerator.ts
- modelina-website/src/helpers/GeneratorCode/PhpGenerator.ts
- modelina-website/src/pages/api/functions/CSharpGenerator.ts
- modelina-website/src/pages/api/functions/CplusplusGenerator.ts
- modelina-website/src/pages/api/functions/PhpGenerator.ts
- modelina-website/src/types/index.ts
- Added namespace support for PHP, C# and C++
Fixes #1351
> chore(website): add namespace options for PHP, C++ and C#

- examples/csharp-generate-handle-nullable/__snapshots__/index.spec.ts.snap
- src/generators/csharp/renderers/ClassRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- I fixed the condition that was completely inverted. Sorry about that!
N/A
@jonaslagoni
> fix: inverted condition for csharp generator handle-nullable

- examples/csharp-generate-handle-nullable/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-handle-nullable/index.ts
- src/generators/csharp/Constants.ts
- src/generators/csharp/renderers/ClassRenderer.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- Fixing the bug for enums and objects
- Added a lot of testing!
> fix: bug when generating null-forgiving for primitives and enums

- docs/champions.md
- modelina-website/src/components/InfoModal.tsx
- modelina-website/src/components/playground/options/GeneralOptions.tsx
this PR tries to fix task 1 of the issue #1392
> chore(website): add info for the general options

- modelina-website/src/components/playground/options/PhpGeneratorOptions.tsx
- This PR adds descriptions for PHP
#1392
> chore(website): add description for PHP

- modelina-website/src/pages/api/functions/CSharpGenerator.ts
-  Merge duplicated import
**Related issue***
Fixes #1530
> chore: fix sonar import warning

- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- src/generators/java/JavaConstrainer.ts
Resolves #1532 
Resolves #1533 
Resolves #1528
> chore: fix warnings

- modelina-website/src/pages/api/functions/CSharpGenerator.ts
- modelina-website/src/pages/api/functions/JavaGenerator.ts
- src/generators/java/JavaGenerator.ts
Resolves #1531 and resolve warning: Prefer using nullish coalescing operator.
Resolves #1534
> chore: remove duplicate import

- examples/csharp-overwrite-enum-naming/index.ts
- examples/integrate-with-react/src/App.js
- examples/javascript-generate-example/index.ts
- examples/javascript-generate-marshalling/index.ts
- examples/passing-interpreter-options/index.ts
- examples/swagger2.0-from-object/index.ts
- modelina-website/src/components/CodeBlock.tsx
- modelina-website/src/components/playground/options/DartGeneratorOptions.tsx
- test/blackbox/blackbox-kotlin.spec.ts
- Resolves Warnings
1. Resolves #1512 
2. Resolves #1513 
3. Resloves #1514 
4. Resolves #1515 
5. Resolves #1516 
6. Resolves #1517 
7. Resolves #1518  
8. Resolves #1519  
9. Resolves #1520  
10. Resolves #1521 
11. Resolves #1522
12. Resolves #1523
13. Resolves #1524
14. Resolves #1525 
15. Resolves #1527 
16. Resolves #1535 
17. Resolves #1536
> chore: resolves warnings

- modelina-website/src/pages/_app.tsx
- package-lock.json
implemented useMemo Hook 
- ...
- ...
- ...
Fixes https://github.com/asyncapi/modelina/issues/1529
> chore(website): implemented useMemo Hook

- docs/migrations/version-1-to-2.md
This PR fixes the links in the migration doc
> docs: fix links in migration to v2 

- CODEOWNERS
With his latest work on the playground: https://github.com/asyncapi/modelina/pull/1628 
I am suggesting we add @devilkiller-ag as a codeowner for the website 💪 
cc @kennethaasan @magicmatatjahu @Ferror @leigh-johnson @Samridhi-98 any objections? 
Lazy consensus will be used with @devilkiller-ag acceptance after 1 week from this PR creation 🙂
> chore: add devilkiller-ag as codeowner

- .github/pull_request_template.md
- Helpful for new contributors to consider being aware about lints and tests before rasing the PR and would eventually help better in maintaining the project.
Based on discussion raised in #1663
> docs: adding PR Template for modelina

- docs/contributing.md
Improved the contributing docs by removing `:tada:`, `:smile:` to :tada: :smile: 
Fix #1697
> docs: improves the contributing docs

- docs/contributing.md
Update emoji types in docs/contribute.md file
Fix https://github.com/asyncapi/modelina/issues/1697
This pull request replaces static unicode emojis with animated ones for better visual appeal. Specifically, it changes ':fire:' to animated 🔥, ':tada:' to animated 🎉, and ':smile:' to animated 😄.
> docs: update Emojis Not Rendering Properly in docs

- modelina-website/src/components/layouts/Footer.tsx
[1726](https://github.com/asyncapi/modelina/issues/1726)
> docs: updated footer with heart emoji

- modelina-website/src/components/docs/Docs.tsx
Fix highlight when selected and hovered in docs of modelina 😃 
Fixes https://github.com/asyncapi/modelina/issues/1719
> docs: fixed highlight in docs

- examples/typescript-generate-jsonbinpack/__snapshots__/index.spec.ts.snap
- src/generators/typescript/presets/JsonBinPackPreset.ts
- test/generators/typescript/preset/__snapshots__/JsonBinPackPreset.spec.ts.snap
- test/runtime/runtime-typescript.ts
- test/runtime/runtime-typescript/test/JsonBinPackPreset.spec.ts
This fixes the jsonbinpack preset and the runtime tests for it.
> fix: jsonbinpack preset and runtime tests

- modelina-website/src/components/layouts/NavBar.tsx
This PR is to redesign the navbar of the website as discussed in issue #1293.
> style(website): redesign navbar

- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
- test/runtime/generic-input.json
- test/runtime/runtime-csharp.ts
- test/runtime/runtime-csharp/runtime-csharp/runtime-csharp.csproj
- test/runtime/runtime-csharp/runtime-csharp/test/models/newtonsoft/Address.cs
This PR fixes that newtonsoft preset could not handle enum values, so I added a runtime test to ensure it works.
Fixes https://github.com/asyncapi/modelina/issues/1263
> fix: newtonsoft could not handle enum values

- README.md
- modelina-website/src/pages/index.tsx
closes: #1751 
These are the current code examples written for performing some operations on generated models:
```
for (const model in models) { 
const generatedCode = model.result;
const dependencies = model.dependencies;
const modeltype = model.type;
const modelName = model.modelName;
}
```
> chore: chang code examples for some operations on generated models

- package-lock.json
- package.json
- src/processors/AsyncAPIInputProcessor.ts
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
This refactors the file path functionality for AsyncAPI input processor, updating the parser dependencies, and fix that the AsyncAPI input is not parsed with the correct parser that support v3.
> fix: file path input for AsyncAPI

- .all-contributorsrc
- README.md
- modelina-website/scripts/build-docs.js
- src/generators/csharp/presets/JsonSerializerPreset.ts
- src/generators/typescript/presets/utils/UnmarshalFunction.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
- test/runtime/generic-input.json
- test/runtime/runtime-csharp/runtime-csharp/test/models/json_serializer/Address.cs
- test/runtime/runtime-csharp/runtime-csharp/test/models/newtonsoft/Address.cs
This PR updates next with the latest master changes
> chore: update next with master changes

- examples/csharp-auto-implemented-properties/index.ts
This PR fixes the example that uses incorrect options.
> chore: fix CSharp auto-implemented properties example

- test/generators/FileGenerators.spec.ts
another attempt after #1899 failed...
> fix: fixes tests for windows

- README.md
- modelina-cli/README.md
This PR adapts the readme files for the CLI.
> docs: update readme files for CLI

- modelina-cli/README.md
Updated tables alignments CLI readme
> chore: updated tables alignments cli readme

- modelina-cli/package.json
This PR fixes the Cli build script for Windows and triggers the release workflow again
> fix: cli build script for windows

- .github/workflows/if-nodejs-pr-testing.yml
This PR tries to fix that PR testing is not running on windows as discussed here: https://github.com/asyncapi/.github/issues/278
> ci: fix PR testing on windows

- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/operation_with_reply.json
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
This PR fixes that the AsyncAPI input processor does not generate messages for replies.
Fixes https://github.com/asyncapi/modelina/issues/1804
> fix: messages are not being generated for AsyncAPI replies

- CODEOWNERS
This pull request adds @akkshitgupta as a code owner of the Avro Schema Input Processor https://github.com/asyncapi/modelina/pull/1753#issuecomment-2081962473
> chore: add Avro Schema Input codeowner

- modelina-cli/src/commands/generate.ts
- modelina-cli/src/helpers/generate.ts
This PR changes when we log what has been generated to let each CLI better handle that.
> feat: add better reusability for the CLI

- README.md
- docs/README.md
- docs/advanced.md
- docs/constraints/README.md
- docs/contributing.md
- docs/internal-model.md
- docs/other-tools.md
- modelina-website/src/pages/index.tsx
PR updates all the broken references found in the docs.
> docs: update broken references

- examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap
> chore: test snapshots

- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
> chore: fix lint

- docs/migrations/README.md
> docs: update migration list

- docs/migrations/version-4-to-5.md
> docs: migration version-4-to-5

- modelina-website/src/pages/index.tsx
Fixes the Broken Links present on the Modelina website.
Fixes #2217.
Clicking on the links now redirects correctly.
> chore: broken links in website

- src/interpreter/InterpretAllOf.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
> fix: infinite loop when having a circular reference with allOf

- docs/languages/Java.md
- examples/java-generate-jakarta-constraint-annotation/index.ts
> docs(java-generator)!: useJakarta was missing and incorrect in documentation

- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
> fix: do not generate discriminator setter when part of parent model for Java

- examples/README.md
- examples/java-generate-optionals-for-non-required-fields/README.md
- examples/java-generate-optionals-for-non-required-fields/__snapshots__/index.spec.ts.snap
- examples/java-generate-optionals-for-non-required-fields/index.spec.ts
- examples/java-generate-optionals-for-non-required-fields/index.ts
- examples/java-generate-optionals-for-non-required-fields/package-lock.json
- examples/java-generate-optionals-for-non-required-fields/package.json
- src/generators/java/JavaGenerator.ts
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
> feat: support Java optionals for non-required fields
