asyncapi/modelina

- src/simplification/Simplify.ts
- src/simplification/SimplifyTypes.ts
- test/simplification/types.spec.ts
This PR ensures that types can be primitives by not resolving into an array all the time. This is to simplify the rendering phase.
> chore: fixed simplification of types removed primitives

- src/simplification/Simplify.ts
- test/simplification/simplify.spec.ts
- test/simplification/simplify/expected/multipleObjects.json
- test/simplification/simplify/multipleObjects.json
This PR fixes that `$id` is preserved in original schema.
> chore: fix $id is preserved in original schema when it should not

- test/simplification/items.spec.ts
- test/simplification/items/expected/multipleObjects.json
- test/simplification/properties.spec.ts
- test/simplification/properties/expected/allOf.json
- test/simplification/properties/expected/allOfNested.json
- test/simplification/properties/expected/anyOf.json
- test/simplification/properties/expected/anyOfNested.json
- test/simplification/properties/expected/basic.json
- test/simplification/properties/expected/combine_properties.json
- test/simplification/properties/expected/conditional.json
- test/simplification/properties/expected/conditionalNested.json
- test/simplification/properties/expected/multiple_objects.json
- test/simplification/properties/expected/oneOf.json
- test/simplification/properties/expected/oneOfNested.json
This PR moves test cases into separated files for simplicity. I simply moved all inline objects into separate expected test outcomes.
> chore: moved tests around

- src/simplification/SimplifyProperties.ts
This PR removes all eslint warnings.
```
/home/runner/work/generator-model-sdk/generator-model-sdk/src/simplification/SimplifyProperties.ts
Warning:   14:25  warning  Refactor this function to reduce its Cognitive Complexity from 35 to the 15 allowed  sonarjs/cognitive-complexity
```
related to #53
> chore: removes eslint warnings from property simplification

- src/processors/AbstractInputProcessor.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- test/processors/AsyncAPIInputProcessor/commonInputModel/basic.json
This PR inherits schema ids from the AsyncAPI parser so the schema ids are deterministic from a templators standpoint. 
fixes #99
> fix: id's from AsyncAPI parser was not preserved

- src/generators/java/JavaRenderer.ts
- src/generators/java/renderers/ClassRenderer.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/generators/javascript/renderers/ClassRenderer.ts
- src/generators/typescript/TypeScriptRenderer.ts
- src/generators/typescript/renderers/ClassRenderer.ts
- src/generators/typescript/renderers/EnumRenderer.ts
- src/generators/typescript/renderers/InterfaceRenderer.ts
- src/generators/typescript/renderers/TypeRenderer.ts
- src/models/Preset.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- Fix issue https://github.com/asyncapi/generator-model-sdk/issues/98
- PascalCase model's name.
- Remove `parentModel` argument - we have `model` and it's the same
- Add missed two function in JavaRenderer: `renderComments` and fix `renderAnnotation`.
- Render type by `format` property if exists in JavaRenderer.
- Update unit tests 
Resolves https://github.com/asyncapi/generator-model-sdk/issues/98
> fix: update JavaRenderer and remove unnecessary code from presets

- src/models/CommonModel.ts
- test/models/CommonModel.spec.ts
This PR adds a helper function to CommonModel which returns all references to other CommonModels. This is useful when you want to add imports and split the models into separate files.
> feat: add support function to get all CommonModel dependencies

- src/simplification/Simplifier.ts
- test/processors/JsonSchemaInputProcessor/commonInputModel/combination_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/references_circular_allOf.json
- test/simplification/extends.spec.ts
This PR switches the default option from extending to merging.
fixes #107
> fix: switch to merging allOf keywords instead of extending them

- src/models/CommonInputModel.ts
- test/processors/AsyncAPIInputProcessor/commonInputModel/basic.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/absence_type.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/applying_conditional_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/combination_schemas.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/enum.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/items.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/multiple_objects.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/object_property_with_anyOf.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/references.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/references_circular.json
- test/processors/JsonSchemaInputProcessor/commonInputModel/references_circular_allOf.json
As in title: remove `customizations` property from `CommonInputModel` class.
> fix: remove customizations property from CommonInputModel class

- src/generators/typescript/TypeScriptRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/JavaRenderer.spec.ts
- test/generators/javascript/JavaScriptRenderer.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
This PR introduces the following changes:
- It removes unused switch case in TypeScript render, CommonModel type cannot be `bigint`
- Added unit tests for JavaRendere, JavaScriptRendere and TypeScriptRenderer
> chore: add unit tests to renderers

- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/commonInputModel/basic.json
- test/processors/AsyncAPIInputProcessor/schema_name_reflection.json
- test/processors/JsonSchemaInputProcessor.spec.ts
This PR introduces two things.
- Added unit test for reflecting schema name based on our parser.
- Fixed a bug where properties, dependencies, and definitions were never iterated.
> fix: some keywords are not iterated for AsyncAPI input

- src/simplification/Simplifier.ts
- src/simplification/SimplifyTypes.ts
- test/simplification/simplify.spec.ts
- test/simplification/types.spec.ts
This PR ensure false schemas are handled more gracefully.
**Related issues**
Fixes #143
> fix: false schemas no longer crash the library

- src/models/CommonModel.ts
- test/models/CommonModel.spec.ts
This PR fixes a problem where the required list of properties is not merged between CommonModels.
Furthermore, this removes duplicate enum values.
fixes #158
> fix: ensure that required list of properties are merged

- src/generators/java/JavaRenderer.ts
- src/generators/typescript/TypeScriptRenderer.ts
- test/generators/java/JavaRenderer.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
This PR fixes a naming issue between referenced models when being rendered as properties.
fixes #168
> fix: referenced models should render their type as pascal case

- src/models/CommonModel.ts
- test/models/CommonModel.spec.ts
This PR introduces some more functions to `CommonModel`, which are going to be used as part of the further refactoring of the simplifier.
Furthermore, I added functionality to ensure that recursive `CommonModel`s are handles correctly when merging. With the current simplifier, this is not a problem so it is not a `fix:`.
> refactor: add support functions for CommonModel

- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/schema_name_reflection.json
This PR fixes the problem where recursive schemas in an AsyncAPI document throws stack size exceeding error.
fixes #199
> fix: recursive schemas in AsyncAPI documents throw an error

- src/generators/java/JavaRenderer.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/generators/javascript/renderers/ClassRenderer.ts
- src/interpreter/Interpreter.ts
- src/models/CommonModel.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/models/CommonModel.spec.ts
This PR fixes an issue with an array of items not supported and then renames the function `getImmediateDependencies` to `getNearestDependencies`.
fixes https://github.com/asyncapi/generator-model-sdk/issues/122
fixes https://github.com/asyncapi/generator-model-sdk/issues/186
> fix: array of items not supported by getNearestDependencies

- src/interpreter/PostInterpreter.ts
- test/interpreter/PostInterpreter.spec.ts
This PR fixes a bug where nested models (i.e. first encountered model is not an object model but the nested one is) are not split.
> fix: nested object models are not split

- docs/interpretation_of_JSON_Schema_draft_7.md
- src/interpreter/InterpretAdditionalItems.ts
- src/interpreter/InterpretAdditionalProperties.ts
- src/interpreter/Interpreter.ts
- src/models/CommonModel.ts
- src/models/CommonSchema.ts
- src/models/Schema.ts
- test/interpreter/unit/Intepreter.spec.ts
- test/interpreter/unit/InterpretAdditionalItems.spec.ts
- test/interpreter/unit/InterpretAdditionalProperties.spec.ts
- test/models/CommonModel.spec.ts
This PR adds the interpretation of `additionalItems` to the interpreter.
fixes #224
> feat: interpret additionalItems

- src/generators/typescript/TypeScriptRenderer.ts
- src/models/CommonModel.ts
- test/blackbox/docs/dummy.json
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
Whenever an array is defined as a tuple, additionalItems control if it is allowed to specify addition items that may be added to the tuples so it acts more like an array.
fixes #260
> feat: render tuple additionalItems for TS

- src/generators/java/JavaRenderer.ts
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaRenderer.spec.ts
This PR renders array type more closely to the underlying structure.
If tuples are encountered the tuple models are combined to ensure that the following CommonModel tuples:
```
items: [
{
type: 'string'
},
{
type: 'string'
}
]
```
are rendered as `String[]` and not `Object[]`.
Furthermore `additionalItems` are taken into account when rendering tuple type to ensure that the appropriate array type is rendered.
fixes #261
> feat: render more accurate array type for Java output

- README.md
Previously the list of supported output languages were duplicated in the `README.md` and the `./generators.md`.
This PR unifies the list of supported output languages, by keeping the list at `./generators.md#supported-languages`. 
This also fixes the fact `Go` was not on the list at `README.md`.
> docs: unify list of supported output languages

- package.json
As in title: publish `esm` modules and TS types - update `prepublishOnly` script.
> fix: publish esm modules and TS types

- src/generators/AbstractGenerator.ts
- src/interpreter/InterpretAdditionalItems.ts
- src/interpreter/InterpretAdditionalProperties.ts
*Description**
Running the example I found that compiling TS gave the following error:
```
node_modules/@asyncapi/modelina/lib/types/generators/AbstractGenerator.d.ts:3:30 - error TS2307: Cannot find module 'models/RenderOutput' or its corresponding type declarations.
3 import { RenderOutput } from 'models/RenderOutput';
```
I noticed the import path was wrong in this case. Fixed that one and a couple more.
> fix: wrong import paths

- src/generators/AbstractGenerator.ts
- src/models/ProcessOptions.ts
- src/models/ProcessorOptions.ts
- src/models/index.ts
- src/processors/AbstractInputProcessor.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/InputProcessor.ts
- test/processors/InputProcessor.spec.ts
This PR introduces ProcessorOptions, which can be used by the processors to change certain behavior of the internals. This is especially useful for example when the library is used in browsers the AsyncAPI processor needs to alter the `path` for derefences.
> feat: pass options to processors

- src/generators/csharp/CSharpRenderer.ts
- test/generators/csharp/CSharpRenderer.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
This PR introduces a change to the underlying C# type rendering. It changes the rendering for `float`, `int` and `bool` to being optional primitives, instead of primitives. As we don't render required properties (yet, gonna do a follow-up issue) we should make them optional.
> fix: c# generator should render types as nullable by default

- src/generators/typescript/presets/CommonPreset.ts
- test/blackbox/Dummy.spec.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
This PR fixes a couple of things: 
1. When enums are referenced, they should be un/marshaled as is, and not through helper functions
2. Ensured that pattern properties and additional properties render the correct un/marshal functionality based on type.
> fix: un/marshal TS class functions did not render references correctly

- src/generators/csharp/index.ts
- src/generators/csharp/presets/JsonSerializerPreset.ts
- src/generators/csharp/presets/index.ts
- src/helpers/FormatHelpers.ts
- test/generators/csharp/presets/JsonSerializerPreset.spec.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
This PR adds functionality to render serializer and deserializer functionality to C# class output. This will enable correct behavior from `System.Text.Json.JsonSerializer.Serialize` and `System.Text.Json.JsonSerializer.Deserialize`, so you can do the following in your code:
```c#
TestModel temp = new TestModel
{
...
};
string json = JsonSerializer.Serialize(temp);
TestModel output = JsonSerializer.Deserialize<TestModel>(json);
```
Partly solves https://github.com/asyncapi/modelina/issues/262
> feat: add c# serializer and deserializer functionality

- README.md
- package-lock.json
- package.json
Because we at the moment don't restrict which node version, it is up to interpretation and can be wrongfully used. We use version 14 for all our GitHub actions, so let's cap it to that.
fixes https://github.com/asyncapi/modelina/issues/160
> fix: restrict node version to >= 14

- src/generators/csharp/renderers/EnumRenderer.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/generators/typescript/renderers/EnumRenderer.ts
- test/generators/AbstractRenderer.spec.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/go/GoGenerator.spec.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
This PR addresses some of the issues revolving around enum generation.
C# need its enum generation fixed beforehand: https://github.com/asyncapi/modelina/issues/336
Fixes https://github.com/asyncapi/modelina/issues/244
Fixes https://github.com/asyncapi/modelina/issues/242
> fix: enum generation should handle union types

- src/generators/typescript/TypeScriptRenderer.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/ExamplePreset.spec.ts.snap
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
This PR fixes a problem where duplicate types was rendered for union types.
fixes https://github.com/asyncapi/modelina/issues/329
> fix: typescript should never render duplicate types

- src/generators/AbstractRenderer.ts
- test/generators/AbstractRenderer.spec.ts
This PR changes the default of the preset rendering, to use the latest non-falsey preset content.
fixes https://github.com/asyncapi/modelina/issues/247
> fix: run presets should be geared towards string output

- src/generators/csharp/renderers/EnumRenderer.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/generators/typescript/renderers/EnumRenderer.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/go/GoGenerator.spec.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
As the title states, enum keys cannot have a number as the first character. This happens for enums that have the value `"1"` as it is seen as a string (so `Number_1` is not prepended).
If the enum generations encounter such a case it prepends `string_${number}` to the key.
> fix: enum keys cannot have a number as first character

- src/generators/csharp/CSharpRenderer.ts
- src/generators/java/JavaRenderer.ts
- src/generators/javascript/JavaScriptRenderer.ts
- src/generators/typescript/TypeScriptRenderer.ts
- src/helpers/NameHelpers.ts
- test/generators/java/JavaRenderer.spec.ts
- test/generators/javascript/JavaScriptRenderer.spec.ts
- test/generators/typescript/TypeScriptRenderer.spec.ts
- test/helpers/NameHelpers.spec.ts
If you have a property name something like `$ref` and `ref` is reserved for that language, the current property naming function would still output `ref` as `$ref` is not transformed until after it is checked.
> fix: some reserved keywords are overlooked

- README.md
I was thinking that the new features would be merged before the new docs, so auto pilot took over when I defined it 😄
> docs: remove unsupported input

- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
This PR adds support for AsyncAPI 2.2.0, as there are no changes affecting this library.
Related to https://github.com/asyncapi/website/pull/324
> feat: support upcomming release of AsyncAPI 2.2.0

- src/generators/typescript/renderers/EnumRenderer.ts
- src/helpers/FormatHelpers.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/helpers/FormatHelpers.spec.ts
I added a Helper Function to resolve ascii characters that are not numbers or letters ([0-9a-zA-Z]) and translate them to english. - becomes minus, + becomes plus ...
The function also accepts characters to be ignored and a seperator string to seperate the translated characters from the rest.
Applied this function to the enum renderer to resolve the issue
Fixes #450
**Tests**
In #450 a blacklisted test is mentioned
> fix: special characters in enum values

- examples/java-generate-tostring/__snapshots__/index.spec.ts.snap
- src/generators/java/presets/CommonPreset.ts
- test/blackbox/blackbox.spec.ts
- test/generators/java/presets/CommonPreset.spec.ts
- test/generators/java/presets/__snapshots__/CommonPreset.spec.ts.snap
This PR cleans up the JavaCommonPreset a bit and fixes a couple of bugs.
- Fixed that we always assumed `additionalProperties` where needed.
- Fixed that if no properties are present it renders accurately.
- Fixed properties with type array did not work.
- Added BlackBox tests for different generator options, which now tests the preset.
Fixes #510
> fix: ensure JavaCommonPreset can be compiled 

- test/blackbox/blackbox.spec.ts
The AsyncAPI dummy document results in duplicate enum keys as described in #504. This PR temporarily disables them.
Related to #504
> test: ignore blackbox documents which is not currently supported

- src/generators/java/renderers/EnumRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
I changed the Java EnumRenderer to sanitize the enum keys by using `FormatHelpers.replaceSpecialCharacters` function in the same way as the Typescript EnumRender already does. 
I also duplicated the test to check that the keys are rendered properly.
Fixes #502
> fix: special characters in java enum values (#502)

- src/generators/java/presets/CommonPreset.ts
- test/generators/java/presets/CommonPreset.spec.ts
- test/generators/java/presets/__snapshots__/CommonPreset.spec.ts.snap
Changed wrong `hash` property in `JavaCommonPresetOptions` to `hashCode` as that the value that is actually used.
Fixes #544
> fix: wrong property name in JavaCommonPresetOptions interface (#544)

- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/schema_with_2_properties_referencing_one_schema.json
Simple change - correctly save converted schemas in `alreadyIteratedSchemas`
Fixes #548
> fix: correctly store already converted schemas while parsing AsyncApi schema (#548)

- examples/asyncapi-from-object/__snapshots__/index.spec.ts.snap
- examples/asyncapi-from-parser/__snapshots__/index.spec.ts.snap
- examples/custom-logging/__snapshots__/index.spec.ts.snap
- examples/generate-typescript-models/__snapshots__/index.spec.ts.snap
- examples/indentation-type-and-size/__snapshots__/index.spec.ts.snap
- examples/json-schema-draft7-from-object/__snapshots__/index.spec.ts.snap
- examples/openapi-from-object/__snapshots__/index.spec.ts.snap
- examples/swagger2.0-from-object/__snapshots__/index.spec.ts.snap
- examples/typescript-enum-type/__snapshots__/index.spec.ts.snap
- examples/typescript-generate-example/__snapshots__/index.spec.ts.snap
- examples/typescript-generate-marshalling/__snapshots__/index.spec.ts.snap
- examples/typescript-interface/__snapshots__/index.spec.ts.snap
- src/generators/typescript/renderers/ClassRenderer.ts
- src/generators/typescript/renderers/EnumRenderer.ts
- src/generators/typescript/renderers/InterfaceRenderer.ts
- src/generators/typescript/renderers/TypeRenderer.ts
- test/blackbox/blackbox.spec.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/generators/typescript/preset/__snapshots__/ExamplePreset.spec.ts.snap
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
The TypeScript renderers do more than provide the base data model, it also exports them and targets ESM module systems. This is a problem because the assumption is that the render renders a base data model that can be built upon after the rendering. 
This PR removes that export functionality.
Related to #536
> fix: removing TypeScript exported base model

- src/generators/csharp/renderers/EnumRenderer.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
I used the helper function `FormatHelpers` similar to #497  to resolve for special characters in the enum renderer for C#. Also wrote down an additional test and updated the jest snapshot.
Fixes #503
> fix: special cases in enum values for C# generator

- docs/advanced.md
- src/generators/csharp/CSharpFileGenerator.ts
- src/generators/csharp/index.ts
- test/generators/csharp/CSharpFileGenerator.spec.ts
- test/generators/csharp/JavaFileGenerator.spec.ts
This PR adds the C# file output generator. 
Fixes https://github.com/asyncapi/modelina/issues/397
> feat: add file output for C# generator

- docs/usage.md
- examples/README.md
- examples/generate-go-models/README.md
- examples/generate-go-models/__snapshots__/index.spec.ts.snap
- examples/generate-go-models/index.spec.ts
- examples/generate-go-models/index.ts
- examples/generate-go-models/package-lock.json
- examples/generate-go-models/package.json
Description
Created example to show how to generate Go data models in
https://github.com/mahakporwal02/modelina/tree/issue/387/examples/generate-go-models
Updated documentation in
https://github.com/mahakporwal02/modelina/blob/issue/387/examples/generate-go-models/README.md
https://github.com/mahakporwal02/modelina/blob/issue/387/examples/README.md
https://github.com/mahakporwal02/modelina/blob/issue/387/docs/usage.md
Performed the implementation for the example.
Updated snapshot for test.
Tests are passing :)
Related issue(s)
Resolves #387 .
> docs: generate go data model

- .sonarcloud.properties
This PR fixes duplication detection between generators, as fixing them, for now, introduces unnecessary complexity. 
Related to https://github.com/asyncapi/modelina/pull/567 and https://github.com/asyncapi/modelina/pull/553
> chore: fixing sonarcloud duplication problems

- src/generators/csharp/CSharpGenerator.ts
- test/blackbox/blackbox.spec.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
There is no need for model dependencies as if they are within the same package, they automatically have access to them.
> fix: model dependencies not needed for C# generator

- docs/languages/Java.md
- examples/README.md
- examples/java-generate-hashcode/README.md
- examples/java-generate-hashcode/__snapshots__/index.spec.ts.snap
- examples/java-generate-hashcode/index.spec.ts
- examples/java-generate-hashcode/index.ts
- examples/java-generate-hashcode/package-lock.json
- examples/java-generate-hashcode/package.json
Description
Added example on how to generate a model to overwrite the hashCode method
https://github.com/mahakporwal02/modelina/tree/issue/422/examples/java-generate-hashcode
Updated documentation.
https://github.com/mahakporwal02/modelina/blob/issue/422/examples/java-generate-hashcode/README.md
https://github.com/mahakporwal02/modelina/blob/issue/422/examples/README.md
https://github.com/mahakporwal02/modelina/blob/issue/422/docs/languages/Java.md
Related issue(s)
fixes #422
> docs: generate Java data models that overwrite hashCode method

- docs/languages/Java.md
- examples/README.md
- examples/java-change-collection-type/README.md
- examples/java-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/java-change-collection-type/index.spec.ts
- examples/java-change-collection-type/index.ts
- examples/java-change-collection-type/package-lock.json
- examples/java-change-collection-type/package.json
- Added example for changing collection types to `List` in Java
- Updated relevant docs
- Added the test and its respective snapshot
Fixes #424
> docs: model to change collection types for Java models

- .github/workflows/coverall.yml
Sometimes, the CI check fails, for weird reasons, almost because it can't find the coverage report, apparently, it is the fault of checkout@v1. https://github.com/coverallsapp/github-action/issues/55
> ci: fix coverage problems with checkout

- examples/csharp-generate-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
The JsonSerializerPreset in C# cant determine the dependency. This PR adds the explicit type.
> fix: missing namespace for Type in C# JsonSerializerPreset

- .github/workflows/blackbox-testing.yml
- .github/workflows/coverall.yml
Adds checks to blackbox tests and coverall to ensure they only run when necessary.
See https://github.com/asyncapi/.github/issues/116#issuecomment-1032521012
> ci: only run workflows when necessary

- CODEOWNERS
- README.md
- docs/champions.md
- docs/contributing.md
- package.json
This PR introduces the champion concept.
Related discussion: https://github.com/asyncapi/modelina/discussions/487
> docs: add champions concept

- examples/csharp-generate-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
I decided to **not** go for the solution proposed earlier in #701. I believe it makes more sense to pass the options block trough to the `Serialize` function. 
This fixes two bugs:
1. Removes the ambiguity introduced in .NET6.0 and will now compile. The function signature used in this fix is supported since the initial release of `JsonSerializer` in .NET Core 3.0 so it should be compatible with all versions.
2. Before during serialization it used the default options to serialize the fields. After this fix the options given during the call to `JsonSerializer.Serialize()` are passed trough. The new output is more inline of what would be expected.
For bug 2 let's take the example: https://github.com/u-packs/modelina-example/blob/example/Models/Auth/AuthMsg.cs
``` c#
AuthMsg …
```
> fix: support net 6.0 for serialization and pass serialization options

- src/generators/go/GoConstrainer.ts
- src/generators/go/GoGenerator.ts
- src/generators/go/constrainer/EnumConstrainer.ts
- src/generators/go/constrainer/ModelNameConstrainer.ts
- src/generators/go/constrainer/PropertyKeyConstrainer.ts
- test/TestUtils/TestRenderers.ts
- test/generators/go/GoConstrainer.spec.ts
- test/generators/go/constrainer/EnumConstrainer.spec.ts
- test/generators/go/constrainer/ModelNameConstrainer.spec.ts
- test/generators/go/constrainer/PropertyKeyConstrainer.spec.ts
This PR converts the Go generator to the new constraint setup introduced in #725
> refactor: convert Go to new constraint setup

- src/generators/typescript/TypeScriptConstrainer.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/generators/typescript/constrainer/EnumConstrainer.ts
- src/generators/typescript/constrainer/ModelNameConstrainer.ts
- src/generators/typescript/constrainer/PropertyKeyConstrainer.ts
- test/TestUtils/TestRenderers.ts
- test/generators/typescript/TypeScriptConstrainer.spec.ts
- test/generators/typescript/constrainer/EnumConstrainer.spec.ts
- test/generators/typescript/constrainer/ModelNameConstrainer.spec.ts
- test/generators/typescript/constrainer/PropertyKeyConstrainer.spec.ts
This PR converts the TS generator to the new constraint setup introduced in https://github.com/asyncapi/modelina/pull/725
> refactor: convert TS to new constraint setup 

- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
As mentioned in #700 the generated serializer code using enums did not match with the enum generated code.
This led to invalid code that required manual fixing. This tiny PR aligns both generators.
Fixes #700
> fix(c#): generated enum extension methods lead to invalid references

- src/generators/csharp/constrainer/PropertyKeyConstrainer.ts
- src/generators/go/constrainer/PropertyKeyConstrainer.ts
- src/generators/java/constrainer/PropertyKeyConstrainer.ts
- src/generators/javascript/constrainer/PropertyKeyConstrainer.ts
- src/generators/typescript/constrainer/PropertyKeyConstrainer.ts
- src/helpers/CommonModelToMetaModel.ts
- src/helpers/ConstrainHelpers.ts
- src/helpers/Splitter.ts
- src/models/ConstrainedMetaModel.ts
- src/models/MetaModel.ts
- test/generators/csharp/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/go/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/java/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/javascript/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/typescript/constrainer/PropertyKeyConstrainer.spec.ts
- test/helpers/Splitter.spec.ts
Two issues I want to solve with this change:
1. In the presets, you need access to the original, non-constrained property, for serialization functionality, and that is not possible with the current setup.
2. Keep it consistent, as we already have the same setup for `EnumValueModel` and `TupleValueModel`.
> refactor: add object property model 

- src/helpers/ConstrainHelpers.ts
- src/helpers/TypeHelpers.ts
- src/models/CommonInputModel.ts
- src/models/ConstrainedMetaModel.ts
- src/models/InputMetaModel.ts
- src/models/OutputModel.ts
- src/models/Preset.ts
- src/models/index.ts
**This PR breaks compilation and jobs will fail which is expected until all the generators have been refactored. So failing jobs are from now on to be ignored.**
This PR introduces a couple of changes:
1. Constrainers no longer have access to the renderer, as they have no reason to and it overcomplicates the entire setup with recursive dependencies. The only reason it was added, was because they needed access to the underlying options, that are now passed along instead.
2. Core models have gotten a new function called `getNearestDependencies` same as the last core model which is to be used to find the nearest dependencies. I am not 100% sure about the implementation and still need to add tests, but with a broken source code, this will be changed later.
3. Introduces …
> chore: refactored model setup to support generators

- src/processors/AbstractInputProcessor.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/InputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- src/processors/SwaggerInputProcessor.ts
- src/processors/TypeScriptInputProcessor.ts
**This PR breaks compilation and jobs will fail which is expected until all the generators have been refactored. So failing jobs are from now on to be ignored.**
This PR refactors all of the input processors to use the new core model and correctly convert them.
Blocked by https://github.com/asyncapi/modelina/pull/766
Related to https://github.com/asyncapi/modelina/pull/764 as we use some of the introduced implementations from there.
> chore: refactored input processors

- README.md
- docs/languages/Csharp.md
- examples/README.md
- examples/csharp-overwrite-enum-naming/README.md
- examples/csharp-overwrite-enum-naming/__snapshots__/index.spec.ts.snap
- examples/csharp-overwrite-enum-naming/index.spec.ts
- examples/csharp-overwrite-enum-naming/index.ts
- examples/csharp-overwrite-enum-naming/package-lock.json
- examples/csharp-overwrite-enum-naming/package.json
This example is to showcase and answer https://stackoverflow.com/questions/72530361/asyncapi-enum-with-specific-values
> docs: add example to use custom enum value name

- examples/README.md
Small spelling mistake (which broke the link)
> docs: fix example link, files not file

- docs/interpretation_of_JSON_Schema.md
- src/helpers/CommonModelToMetaModel.ts
- src/interpreter/InterpretPatternProperties.ts
- src/interpreter/PostInterpreter.ts
- src/models/CommonModel.ts
- test/helpers/CommonModelToMetaModel.spec.ts
- test/interpreter/PostInterpreter.spec.ts
- test/interpreter/unit/patternProperties.spec.ts
This PR changes the functionality for how patternProperties are interpreted, by merging the structures into `additionalProperties` to only have a single property that contains all "extra" properties. 
This change is because Modelina does not have runtime constraints (and might never have, or at least far out in the future), which means you cannot really have multiple dictionaries with unwrapping serialization options. This makes sure JSON Schema never creates that scenario.
> refactor: switch interpretation of pattern properties

- src/generators/csharp/CSharpGenerator.ts
- src/generators/dart/DartGenerator.ts
- src/generators/go/GoGenerator.ts
- src/generators/java/JavaGenerator.ts
- src/generators/javascript/JavaScriptGenerator.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/helpers/ConstrainHelpers.ts
- test/helpers/ConstrainHelpers.spec.ts
This PR adds a fix and basic tests to constrain helpers as it was a blocker for fixing generator tests.
> refactor: fix constrain helpers and add test

- test/helpers/TypeHelpers.spec.ts
This PR fixes the TypeHelpers tests
> chore: fix TypeHelpers tests

- test/TestUtils/TestGenerator.ts
- test/TestUtils/TestRenderers.ts
- test/generators/AbstractGenerator.spec.ts
- test/generators/AbstractRenderer.spec.ts
This PR fixes the Abstract generator and renderer tests
> chore: fix generator and renderer tests

- test/models/CommonModel.spec.ts
As we removed the patternProperty for CommonModel this test is no longer needed.
> chore: remove unnecessary common model test

- src/models/ConstrainedMetaModel.ts
- test/models/ConstrainedMetaModel.spec.ts
This PR fixes and tests the `containsPropertyType` function from the ObjectModel
> chore: fix contains property check failing

- src/generators/java/JavaPreset.ts
- src/generators/java/presets/JacksonPreset.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/models/Preset.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/presets/DescriptionPreset.spec.ts
- test/generators/java/presets/JacksonPreset.spec.ts
- generate Jackson annotations for Java enums only with Jackson Preset
- update all relevant tests
Fixes #812
> fix: generate Jackson annotations for Java enums only with Jackson Preset

- package.json
This PR tries again to trigger a new release by switching the version to `v1.0.0-next.2` as I was unable to remove the existing tag for `v1.0.0-next.1` (missing permissions and everyone on holiday)... See https://github.com/asyncapi/modelina/runs/7601164827?check_suite_focus=true
> feat: trigger new release

- docs/advanced.md
- docs/languages/Csharp.md
- docs/languages/Dart.md
- docs/languages/Java.md
- docs/languages/JavaScript.md
- docs/languages/TypeScript.md
- package.json
This PR aims to update the language documentation about serializing models and make them uniform and set the documentation up for further presets.
> docs: update language documentation

- src/generators/typescript/TypeScriptConstrainer.ts
- test/generators/typescript/TypeScriptConstrainer.spec.ts
There does not exist a type called `interger` for typescript numbers.
This change is part of fixing the black-box tests.
> fix: wrong typescript number type used for integers

- src/models/CommonModel.ts
- test/generators/typescript/TypeScriptGenerator.spec.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/models/CommonModel.spec.ts
- Please check the Pet test in the MR. This fix makes sure that `CommonModel.mergeProperties` doesn't carry over any properties to other models when trying to merge Pet into multiple schemas.
> fix: merging CommonModel properties should not carry over properties to other models

- src/helpers/ConstrainHelpers.ts
- src/models/ConstrainedMetaModel.ts
- src/utils/DependencyHelper.ts
- test/helpers/ConstrainHelpers.spec.ts
- test/models/ConstrainedMetaModel.spec.ts
- test/utils/DependencyHelper.spec.ts
In the current implementation, we sometimes render duplicate and self-dependencies, which makes some black-box tests fail.  This PR fixes this issue.
This change is part of fixing the black-box tests.
> fix: duplicate and self dependencies should not being rendered

- src/generators/python/renderers/ClassRenderer.ts
- test/generators/python/PythonGenerator.spec.ts
- test/generators/python/__snapshots__/PythonGenerator.spec.ts.snap
If the class generator tries to render one with no properties, the class file is unable to compile. 
This change is part of fixing the black-box tests.
> fix: python generate unusable class for empty properties

- src/generators/javascript/JavaScriptGenerator.ts
- test/generators/javascript/JavaScriptGenerator.spec.ts
- test/generators/javascript/__snapshots__/JavaScriptGenerator.spec.ts.snap
In the current JavaScript generator the enums are split out but never rendered because we don't have a way to render them.
The reason why this change is necessary, is because classes still try to import/require the enums, when they simply don't exist. Which means something like the black-box tests fails.
Part of https://github.com/asyncapi/modelina/pull/905
> fix: javascript should not split out enums

- src/generators/typescript/presets/CommonPreset.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
This PR fixes two issues with the preset. 
1. The unmarshal code does not handle external models correctly
2. The unmarshal code does not handle dictionary properties correctly
3. The marshal code does not handle external models correctly
Fixes https://github.com/asyncapi/modelina/issues/909
> fix: typescript marshalling preset not caring about external models  

- src/generators/typescript/TypeScriptConstrainer.ts
- test/generators/typescript/TypeScriptConstrainer.spec.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
This PR fixes an issue where an array with union type renders it incorrectly.
Fixes https://github.com/asyncapi/modelina/issues/914
Part of https://github.com/asyncapi/modelina/pull/905
> fix: typescript rendering wrong array type when union

- src/generators/java/JavaConstrainer.ts
- test/generators/java/JavaConstrainer.spec.ts
This PR fixes an issue where the simple `int` type is not allowed for map values.
Fixes https://github.com/asyncapi/modelina/issues/922
Related to #905
> fix: java dictionary constrainer gives unusable integer type for map value

- src/generators/typescript/presets/CommonPreset.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
- fixes renderUnmarshalProperty for typescript
> fix: remove unintended characters for typescript marshalling preset

- examples/asyncapi-from-parser/index.ts
- examples/integrate-with-react/package.json
- jest.config.js
- package-lock.json
- package.json
- src/models/ProcessorOptions.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/InputProcessor.spec.ts
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
Integrate new ParserJS version:
- use new version of `parser-js`
- update library tests and examples tests
Part of https://github.com/asyncapi/parser-js/issues/481
> feat: integrate new ParserJS version

- src/models/ProcessorOptions.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- src/processors/SwaggerInputProcessor.ts
- src/processors/TypeScriptInputProcessor.ts
This is a small refactoring PR to ensure that all the `processors` have access to `processorOptions` which is passed via `process(...)` method.
Also it adds `interpreterOptions` to `processorOptions` under `interpreter` and it ensures that `interpreter.interpret(...)` receives `interpreterOptions` that is referenced from `processorOptions`.
https://github.com/asyncapi/modelina/issues/916
> fix: enable processor options to be passed processors

- src/processors/JsonSchemaInputProcessor.ts
This is a tiny fix as follow up to #920. `JsonSchemaInputProcessor` didn't pass `ProcessorOptions` to all `processDraft...` private methods.
> fix: pass processor options to JSON schema input processor

- src/generators/java/JavaConstrainer.ts
- src/generators/java/renderers/EnumRenderer.ts
- test/generators/java/JavaConstrainer.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
This PR ensures that enums have accurate value types based on different parameters.
I also double-checked with the black-box tests that they no longer had any issues.
Fixes https://github.com/asyncapi/modelina/issues/390
> fix: enum generator for Java should use strict types for it's values

- .eslintignore
- README.md
- docs/contributing.md
- jest.config.js
- package.json
- src/generators/AbstractGenerator.ts
- src/generators/java/JavaConstrainer.ts
- src/generators/java/renderers/EnumRenderer.ts
- src/processors/AbstractInputProcessor.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/InputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- src/processors/SwaggerInputProcessor.ts
- src/processors/TemplateInputProcessor.ts
- src/processors/TypeScriptInputProcessor.ts
- test/processors/InputProcessor.spec.ts
- test/processors/TemplateInputProcessor.spec.ts
- tsconfig.json
This PR adds contribution guidelines and a template processor for adding new ones more easily. 
This PR also contains the following changes:
- Changed the old `Record<string, unknown>` input type to `any` because we should be able to process any type of input.
- Fixed an issue where templates are collected for coverage
- Add new contribution guidelines for new processors
- Add new input processor template and test
- Removed unused script ignore command
> docs: add contribution guidelines for processors

- .github/workflows/if-nodejs-release.yml
This PR fixes that the `next` branch is not getting released
> ci: fix `next` branch is not getting released

- examples/rust-generate-crate/__snapshots__/index.spec.ts.snap
- src/generators/rust/RustConstrainer.ts
- src/generators/rust/RustFileGenerator.ts
- src/generators/rust/RustRenderer.ts
- src/generators/rust/constrainer/ModelNameConstrainer.ts
- src/generators/rust/presets/CommonPreset.ts
- src/generators/rust/renderers/StructRenderer.ts
- src/generators/rust/renderers/UnionRenderer.ts
- src/helpers/FormatHelpers.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/generators/rust/RustGenerator.spec.ts
- test/generators/rust/RustRenderer.spec.ts
- test/generators/rust/__snapshots__/RustGenerator.spec.ts.snap
- test/generators/rust/presets/CommonPreset.spec.ts
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
Locally tried Rust generator with more complicated private examples and got some compile errors in the generate Rust crate.
The PR makes compile pass fixing the following issues:
* Remove warnings in case the model name contains the dash + number (e.g. `Abc_123`)
* Compile errors due to mismatch of some Option field definitions and constructors in struct 
* Fix broken generated file names
* Fix invalid type name included in generated Union types
* Fix the missing qualifer `crate::` in some cases
* Fix undefined error when schemaUid doesn't exist
> fix: rust compile errors

- examples/rust-generate-crate/__snapshots__/index.spec.ts.snap
- src/generators/rust/RustConstrainer.ts
- src/generators/rust/RustFileGenerator.ts
- src/generators/rust/RustRenderer.ts
- src/generators/rust/constrainer/ModelNameConstrainer.ts
- src/generators/rust/presets/CommonPreset.ts
- src/generators/rust/renderers/UnionRenderer.ts
- src/helpers/FormatHelpers.ts
- src/processors/AsyncAPIInputProcessor.ts
- test/generators/rust/RustGenerator.spec.ts
- test/generators/rust/RustRenderer.spec.ts
- test/generators/rust/__snapshots__/RustGenerator.spec.ts.snap
- test/generators/rust/presets/CommonPreset.spec.ts
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
Continuation of: https://github.com/asyncapi/modelina/pull/869
Figured I should get this PR cleaned up and merged before rolling up my sleeves to fix Rust black-box tests.
**Original PR Description**
Locally tried Rust generator with more complicated private examples and got some compile errors in the generate Rust crate.
The PR makes compile pass fixing the following issues:
* Remove warnings in case the model name contains the dash + number (e.g. `Abc_123`)
* Compile errors due to mismatch of some Option field definitions and constructors in struct 
* Fix broken generated file names
* Fix invalid type name included in generated Union types
* Fix the missing qualifer `crate::` in some cases
* Fix undefined error when schemaUid doesn't exist
> fix: rust compile errors on enum members containing digits

- src/generators/python/Constants.ts
- test/generators/python/Constants.spec.ts
This PR adds the missing reserved keyword `exec` for python that failed black-box tests.
> fix: add `exec` as reserved keyword for Python

- src/generators/rust/constrainer/EnumConstrainer.ts
- src/generators/rust/renderers/EnumRenderer.ts
- test/generators/rust/constrainer/EnumConstrainer.spec.ts
This PR fixes a problem with the Rust enum renderer that assumes JSON Schema inputs. I also converted the enum value constrainer not to constrain the JSON value and then added a support function in the enum renderer to render the enum value type. To align with the other generators.
We might need to add something along the lines of `valueType` to the `ConstrainedEnumValueModel` 🤔
> fix: rust enum renderer only working for JSON Schema inputs

- src/helpers/ConstrainHelpers.ts
- src/helpers/TypeHelpers.ts
- test/helpers/ConstrainHelpers.spec.ts
- test/helpers/TypeHelpers.spec.ts
This PR adds the possibility to access the entire constrained property object.
Earlier part of https://github.com/asyncapi/modelina/pull/947
> feat: add access to entire property object in constrainer

- examples/rust-generate-crate/__snapshots__/index.spec.ts.snap
- src/generators/rust/presets/CommonPreset.ts
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
I upgraded to `1.0.0-next.30` and noticed Rust's `new()` function implementation is broken for any schema with a `$ref` to another schema.
Schema where I first noticed this issue: https://github.com/bitsy-ai/printnanny-asyncapi-schema/blob/main/2.4.0/printnanny-os.yml
Edit: I also noticed indentation is off by 4 spaces in struct implementation fns. I fixed that as well: https://github.com/asyncapi/modelina/pull/1013/commits/0db9d9f09f90c5d2ad2fec1a4360571a186f929d
closes issue #1012
> fix: rust impl new fn for Boxed values

- examples/rust-generate-crate/__snapshots__/index.spec.ts.snap
- src/generators/rust/renderers/StructRenderer.ts
- test/generators/rust/__snapshots__/RustGenerator.spec.ts.snap
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
RustGenerator outputs structs missing the `pub` keyword. Without `pub`, these fields are private to the implementation of the struct. 
closes: https://github.com/asyncapi/modelina/issues/1020
> fix: structs missing pub keyword in RustGenerator

- src/generators/rust/Constants.ts
- src/generators/rust/constrainer/EnumConstrainer.ts
- src/generators/rust/constrainer/ModelNameConstrainer.ts
- src/generators/rust/constrainer/PropertyKeyConstrainer.ts
- test/generators/rust/__snapshots__/RustGenerator.spec.ts.snap
- test/generators/rust/constrainer/EnumConstrainer.spec.ts
- test/generators/rust/constrainer/ModelNameConstrainer.spec.ts
- test/generators/rust/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
This PR makes sure that reserved keywords are case-sensitive to make sure `Static` is not rendered as `ReservedStatic`. I also added specific tests for the constraint rules.
Fixes #1030
> fix: reserved keywords in Rust should be case-sensitive

- README.md
- examples/README.md
- package.json
After reading https://brew.sh/ main readme page, I noticed how quickly you get displayed exactly what it helps you with, and with Modelina I felt that it would take quite a read before you got to the point of a quick overview. 
So I did a few modifications using the similar concept they used with showing some of the core features Modelina provides up front 😄 
Oh, yea and I grouped the examples list just to get a better overview 😆
> docs: improve readme with use-cases and examples

- src/generators/java/JavaConstrainer.ts
- src/generators/java/JavaDependencyManager.ts
- src/generators/java/JavaGenerator.ts
- src/generators/java/JavaRenderer.ts
- src/generators/java/presets/CommonPreset.ts
- src/generators/java/presets/ConstraintsPreset.ts
- src/generators/java/presets/JacksonPreset.ts
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaConstrainer.spec.ts
- test/generators/java/JavaRenderer.spec.ts
This PR adds the new dependency manager alongside a few changes:
> chore: add dependency manager for Java

- src/generators/AbstractDependencyManager.ts
- src/generators/csharp/CSharpConstrainer.ts
- src/generators/csharp/CSharpDependencyManager.ts
- src/generators/csharp/CSharpFileGenerator.ts
- src/generators/csharp/CSharpGenerator.ts
- src/generators/csharp/CSharpRenderer.ts
- src/generators/csharp/presets/CommonPreset.ts
- src/generators/csharp/presets/JsonSerializerPreset.ts
- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
- src/generators/csharp/renderers/ClassRenderer.ts
- test/generators/csharp/CSharpConstrainer.spec.ts
- test/generators/csharp/CSharpRenderer.spec.ts
This PR adds the new dependency manager to the CSharp generator alongside a few changes:
> chore: add dependency manager to CSharp

- src/generators/dart/DartConstrainer.ts
- src/generators/dart/DartDependencyManager.ts
- src/generators/dart/DartGenerator.ts
- src/generators/dart/DartRenderer.ts
- src/generators/dart/presets/JsonSerializablePreset.ts
- test/generators/dart/DartConstrainer.spec.ts
- test/generators/dart/DartRenderer.spec.ts
This PR adds the new dependency manager alongside a few changes:
> chore: add dependency manager for Dart

- src/generators/go/GoConstrainer.ts
- src/generators/go/GoDependencyManager.ts
- src/generators/go/GoGenerator.ts
- src/generators/go/GoRenderer.ts
- test/generators/go/GoConstrainer.spec.ts
- test/generators/go/GoRenderer.spec.ts
This PR adds the new dependency manager alongside a few changes:
> chore: add dependency manager for Go

- examples/csharp-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-equals-and-hashcode/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-required-properties/__snapshots__/index.spec.ts.snap
- examples/csharp-use-inheritance/__snapshots__/index.spec.ts.snap
- examples/generate-csharp-models/__snapshots__/index.spec.ts.snap
- src/generators/csharp/CSharpConstrainer.ts
- src/generators/csharp/CSharpRenderer.ts
- src/generators/csharp/presets/JsonSerializerPreset.ts
- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
- src/generators/csharp/renderers/ClassRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/CommonPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
- Using ConstrainedObjectPropertyModel to get info on if the property is required
Fixes #941
> fix: csharp generator not render optional types for optional properties

- examples/java-generate-jackson-annotation/__snapshots__/index.spec.ts.snap
- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
This is a small fix for Java Jackson preset. To make sure that Jackson serialization works in all situations the recommended way is to add Jackson annotations at the field level.
https://github.com/asyncapi/modelina/issues/983
> fix: add Jackson annotations at the field level

- src/generators/python/PythonConstrainer.ts
- src/generators/python/PythonDependencyManager.ts
- src/generators/python/PythonGenerator.ts
- src/generators/python/PythonRenderer.ts
- src/generators/python/presets/Pydantic.ts
- src/generators/python/renderers/EnumRenderer.ts
- test/generators/python/PythonConstrainer.spec.ts
- test/generators/python/PythonRenderer.spec.ts
This PR adds the new dependency manager alongside a few changes:
> chore: add dependency manager for Python

- src/generators/kotlin/KotlinConstrainer.ts
- src/generators/kotlin/KotlinDependencyManager.ts
- src/generators/kotlin/KotlinGenerator.ts
- src/generators/kotlin/KotlinRenderer.ts
- src/generators/kotlin/presets/ConstraintsPreset.ts
- test/generators/kotlin/KotlinDependencyManager.spec.ts
This PR adds the final piece to the puzzle ([before releasing the feature](https://github.com/asyncapi/modelina/pull/1063)) and adds the dependency manager to Kotlin.
This is a core Modelina feature replicated across all generators that enables a few things.
1. It lets users add dependencies for models during the constraint phase, i.e. solving: https://github.com/asyncapi/modelina/issues/546#issuecomment-1209340325
2. It enables greater separation of logic for handling dependencies within one specific file instead of it being part of the renderer.
3. Subsequently the architecture enables greater precision of rendering models where we now have 3 different levels of options: https://github.com/asyncapi/modelina/pull/1063/files#diff-72376d0b487d7231cf31959bf266f6aea098e899743b …
> chore: add dependency manager for Kotlin

- src/interpreter/InterpretAdditionalItems.ts
- src/interpreter/InterpretAdditionalProperties.ts
- src/interpreter/Interpreter.ts
- test/interpreter/unit/InterpretAdditionalItems.spec.ts
- test/interpreter/unit/InterpretAdditionalProperties.spec.ts
This PR fixes the two options always ignoring additionalProperties and additionalItems when it should be conditional on two things:
1. Should only apply on when defaulting, not when explicitly defined.
2. ignoreAdditionalProperties should only apply when the schema has properties, otherwise its normally later interpreted as a map type which is intended.
3. ignoreAdditionalProperties should only apply when the schema has explicit types defined, otherwise its the same as setting types explicitly.
> fix: add conditions for when to ignore additionalProperties and additionalItems

- docs/migrations/version-1-to-2.md
- examples/csharp-auto-implemented-properties/__snapshots__/index.spec.ts.snap
- examples/csharp-change-collection-type/__snapshots__/index.spec.ts.snap
- src/helpers/CommonModelToMetaModel.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/go/__snapshots__/GoGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/CommonPreset.spec.ts.snap
- test/generators/rust/presets/CommonPreset.spec.ts
- test/generators/rust/presets/__snapshots__/CommonPreset.spec.ts.snap
- test/generators/typescript/__snapshots__/TypeScriptGenerator.spec.ts.snap
- test/helpers/CommonModelToMetaModel.spec.ts
When I first created this logic I mistakenly thought `additionalItems` was applied to non-tuple array types i.e. when you use a single entry for `items`. This is not the case.
This PR:
- fixes that implementation and adapts the tests.
- add migration guidelines for how the models change.
Fixes https://github.com/asyncapi/modelina/issues/1138
> fix!: additionalItems being applied for regular arrays

- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts
- modelina-website/src/pages/api/functions/TypeScriptGenerator.ts
- modelina-website/src/types/index.ts
- Add support for selecting enumType in playground
Fixes #1162
> chore(website): add enumtype selection in the playground for typescript

- docs/languages/Csharp.md
- examples/README.md
- examples/csharp-generate-records/README.md
- examples/csharp-generate-records/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-records/index.spec.ts
- examples/csharp-generate-records/index.ts
- examples/csharp-generate-records/package-lock.json
- examples/csharp-generate-records/package.json
- src/generators/csharp/CSharpGenerator.ts
- src/generators/csharp/CSharpPreset.ts
- src/generators/csharp/Constants.ts
- src/generators/csharp/renderers/RecordRenderer.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
This PR adds an option to the C# generator allowing it to render records instead of classes. This is done using a new renderer that implements `self`, `property` and `additionalContent` hooks. It does not support using the `autoimplementedProperties` as option as this is instead a default when generating records.
Resolves #1153
> feat: add option to Csharp generator allowing user to generate records instead of classes

- src/generators/typescript/presets/CommonPreset.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
For the arrays used to store union and array values, it can be more than just string type, and this is being complained about when transpiling the files.
> fix: typescript serialization using wrong typings

- examples/php-generate-complete-models/README.md
- examples/php-generate-complete-models/__snapshots__/index.spec.ts.snap
- examples/php-generate-complete-models/index.spec.ts
- examples/php-generate-complete-models/index.ts
- examples/php-generate-complete-models/package-lock.json
- examples/php-generate-complete-models/package.json
- src/generators/php/PhpGenerator.ts
- src/generators/php/PhpRenderer.ts
- src/generators/php/presets/DescriptionPreset.ts
- src/generators/php/renderers/ClassRenderer.ts
- src/generators/php/renderers/EnumRenderer.ts
- test/generators/php/PhpGenerator.spec.ts
- test/generators/php/PhpRenderer.spec.ts
- test/generators/php/__snapshots__/PhpGenerator.spec.ts.snap
- test/generators/php/presets/__snapshots__/DescriptionPreset.spec.ts.snap
1. Added the Generate Complete Models Example
2. Moved the rendering `<?php` tag to rendering complete model
3. Rendering class descriptions
4. Rendering Strict Types declaration as default
> feat: php generator - descriptions, rendering model vs rendering file, example of complete model

- docs/languages/Php.md
- examples/README.md
- src/generators/php/PhpGenerator.ts
PHP has the concept of namespaces (like C#) instead of packages (like Java) so to have it coherent I renamed it
> feat: php generator - rename packageName to namespace

- src/interpreter/InterpretAllOf.ts
- src/interpreter/InterpretOneOf.ts
- src/interpreter/InterpretOneOfWithAllOf.ts
- src/interpreter/InterpretOneOfWithProperties.ts
- src/interpreter/InterpretProperties.ts
- src/models/CommonModel.ts
- test/interpreter/unit/InterpretAllOf.spec.ts
- test/interpreter/unit/InterpretOneOf.spec.ts
- test/interpreter/unit/InterpretOneOfWithAllOf.spec.ts
- test/interpreter/unit/InterpretProperties.spec.ts
- test/interpreter/unit/interpretOneOfWithProperties.spec.ts
This is a preparation PR to support union for objects in Java (https://github.com/asyncapi/modelina/pull/1264). It adds `discriminator` in the CommonModel, and the interpreters set that value when they should.
- adds `discriminator` in the CommonModel
- sets `discriminator` in the interpreters
> refactor: adds discriminator in CommonModel and interpreters

- .all-contributorsrc
- CODEOWNERS
As I've practically not put any all that much time into modelina, since I first joined as a contributor, and won't be able to do so in the future, I'd step down as contributor/codeowner etc. 
I'll probably do the same for the TSC, as my focus shifted away from cloud and messaging related stuff.
> chore: remove LouisXhaferi from codeowners

- docs/migrations/version-1-to-2.md
- examples/generate-kotlin-models/__snapshots__/index.spec.ts.snap
- examples/kotlin-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/kotlin-generate-javax-constraint-annotation/__snapshots__/index.spec.ts.snap
- examples/kotlin-generate-kdoc/__snapshots__/index.spec.ts.snap
- src/generators/kotlin/renderers/ClassRenderer.ts
- test/generators/kotlin/__snapshots__/KotlinGenerator.spec.ts.snap
- test/generators/kotlin/presets/__snapshots__/ConstraintsPreset.spec.ts.snap
- test/generators/kotlin/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- Update default Kotlin renderer to make non-required properties nullable and `null` by default.
- Updated snapshots
Fixes #1273
Retarget of #1274
> fix!: update default Kotlin renderer to make non-required properties nullable

- src/generators/rust/renderers/UnionRenderer.ts
- update Rust `UnionRenderer` to use `ConstrainedMetaModelOptionsDiscriminator` rather than reference the `model.originalInput`
#1270
> chore: update Rust union render to use ConstrainedMetaModelOptionsDiscriminator

- src/interpreter/InterpretAllOf.ts
- src/interpreter/InterpretConst.ts
- src/interpreter/InterpretOneOf.ts
- src/interpreter/InterpretOneOfWithAllOf.ts
- src/interpreter/InterpretOneOfWithProperties.ts
- src/interpreter/Interpreter.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- test/generators/java/presets/JacksonPreset.spec.ts
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
- test/interpreter/unit/InterpretAllOf.spec.ts
- test/interpreter/unit/InterpretOneOf.spec.ts
- test/interpreter/unit/Interpreter.spec.ts
- Add `discriminator` support for `OpenAPI` and `Swagger` schema
Follows on from #1271, #1270, #1269 and  #1169
> feat!: add discriminator support for OpenAPI v3 and Swagger v2

- docs/migrations/version-1-to-2.md
- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
- Use EXISTING_PROPERTY as JsonTypeInfo.As annotation to avoid duplicates when serializing (ref https://fasterxml.github.io/jackson-annotations/javadoc/2.4/com/fasterxml/jackson/annotation/JsonTypeInfo.As.html)
> feat!: use EXISTING_PROPERTY as JsonTypeInfo.As annotation to avoid duplicates when serializing

- modelina-website/scripts/build-examples.js
This PR replaces relative references `../some-other-example` to other examples to query params `?selectedExample=some-other-example`
This fixes the link in https://modelina.org/examples?selectedExample=overwrite-default-constraint that links to the incorrect https://modelina.org/overwrite-naming-formatting/ to be /examples?selectedExample=overwrite-naming-formatting instead
> chore(website): fix relative reference in description of examples

- modelina-website/src/pages/api/functions/PhpGenerator.ts
I overlooked the namespace name. PHP must have namespaces separated by `\` 😄
> chore(website): change default playground namespace for PHP

- modelina-website/src/components/playground/options/CplusplusGeneratorOptions.tsx
- modelina-website/src/components/playground/options/GoGeneratorOptions.tsx
- modelina-website/src/components/playground/options/KotlinGeneratorOptions.tsx
this PR tries to add info to options for the language c++, kotlin and go as mentioned in issue #1392
> chore(website): add info to options for c++, kotlin, and go

- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
Part of Add descriptions for options in playground continued.. #1392
> chore(website): add C# options descriptions in the playground

- .github/workflows/if-nodejs-release.yml
This is just a temporary fix for the release workflow, as we should use `next-major` instead of just `next`.
> ci: temporarily enable release for next

- src/generators/javascript/presets/CommonPreset.ts
- src/generators/typescript/presets/CommonPreset.ts
- test/generators/javascript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
- test/generators/typescript/preset/__snapshots__/JsonBinPackPreset.spec.ts.snap
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
This PR fixes a bug where wrong property names are filtered for typescript and js generator.
This fixes the runtime testing problems.
Fixes https://github.com/asyncapi/modelina/issues/1391
> fix: ts/js unmarshalling function bug

- modelina-website/scripts/build-examples.js
Improved the example display names on the examples page by making a function to modify the string.
Resolves #1417
> chore(website): improve the example display name

- modelina-website/scripts/build-examples.js
- modelina-website/src/components/layouts/MobileNavMenu.tsx
Issue #1431 fixed, changes the mobile nav menu to include API docs link.
Fixes https://github.com/asyncapi/modelina/issues/1431
> chore(website): fix missing link to API docs in mobile view

- src/generators/php/renderers/EnumRenderer.ts
- test/generators/php/PhpGenerator.spec.ts
- test/generators/php/__snapshots__/PhpGenerator.spec.ts.snap
When using the preset option `additionalContent`, the content was not added to the PHP enum.
> fix: additional content presets for PHP enums are not applied

- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
Use pascalCase in JSON Serializer preset
Fixes #1448 
**Test Run Output**
[test.txt](https://github.com/asyncapi/modelina/files/12286854/test.txt)
> fix: dotnet JSON Serializer preset does not access accessors

- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
When deserializing `oneOf` structures using non-const discriminators, the discriminator value is not visible in the deserialized model.
Add `visible=true` to `@JsonTypeInfo`
This doesn't change the behaviour when using const discriminators.
> feat: make discriminator property visible to deserializer from Java Jackson preset

- src/generators/typescript/TypeScriptObjectRenderer.ts
Fixed an issue where a constant in an interface model type would try to assign a value to the variable, which resulted in invalid TypeScript. Tested with both class and interface modeltypes. Issue described in comments of #1471
> fix: typescript interface variable assignment

- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- Fix generation problem at 2 places when using C# generator with json serializer option
* Missing "s" for a class
* Missing "value." when deserializing.
> fix: problem with json serializer option with C# generator

- docs/languages/Php.md
- examples/php-generate-json-serializable-preset/README.md
- examples/php-generate-json-serializable-preset/__snapshots__/index.spec.ts.snap
- examples/php-generate-json-serializable-preset/index.spec.ts
- examples/php-generate-json-serializable-preset/index.ts
- examples/php-generate-json-serializable-preset/package-lock.json
- examples/php-generate-json-serializable-preset/package.json
- src/generators/php/presets/JsonSerializablePreset.ts
- src/generators/php/presets/index.ts
- test/generators/php/presets/JsonSerializablePreset.spec.ts
- test/generators/php/presets/__snapshots__/JsonSerializablePreset.spec.ts.snap
In PHP objects (and also arrays and scalars) can be serialized to JSON using the function `json_encode()`. In order to maintain the correct property names and values for Enums, normalization of values needs to be implemented manually using the `JsonSerializable` interface.
The serialization to JSON can be enabled by using the optional preset `PHP_JSON_SERIALIZABLE_PRESET`.
This way of serializing PHP objects does not require any user land package and works out of the box with each PHP version. It is also compatible with different serialization frameworks, like Symfony.
> feat: add PHP JsonSerializable Preset

- src/processors/OpenAPIInputProcessor.ts
- test/processors/OpenAPIInputProcessor.spec.ts
- test/processors/OpenAPIInputProcessor/basic.json
- test/processors/__snapshots__/OpenAPIInputProcessor.spec.ts.snap
Models that were only present in OpenAPIV3 parameters were not being generated. This was causing problems for parameters with schema like `enum` that can be reflected in the language type system.
> feat!: generate models for OpenAPI parameters

- test/generators/AbstractGenerator.spec.ts
> chore: remove unused import of 'CommonModel'

- docs/README.md
- modelina-website/scripts/build-docs.js
- modelina-website/src/components/docs/Docs.tsx
This PR fixes the github links for editing the page to display correctly.
> chore(website): fix github edit links for docs

- .asyncapi-tool
- Removes field to prevent script from failing to add it to asyncapi website
Fixes https://github.com/asyncapi/modelina/issues/1555
> chore: remove isAsyncAPIOwner field from .asyncapi-tool

- src/generators/java/JavaRenderer.ts
- src/generators/java/constrainer/ConstantConstrainer.ts
- src/generators/java/presets/ConstraintsPreset.ts
- test/generators/java/JavaRenderer.spec.ts
- test/generators/java/presets/ConstraintsPreset.spec.ts
- test/generators/java/presets/__snapshots__/ConstraintsPreset.spec.ts.snap
- Java string constants were being rendered without escaping. This could generate invalid java. This was a particular issue for regex patters as these frequently include the `\` character
> fix: escape java string literals used for regex patterns and string constants

- docs/migrations/version-1-to-2.md
This PR updates the migration guide from v1 to v2 with the missing breaking changes commits.
This is one of the last changes before v2 release.
> chore: update migration guide

- src/helpers/CommonModelToMetaModel.ts
**Downgrade AnyModel error to a warning**
This is needed to prevent the asyncapi CLI from aborting when an AnyModel is encountered.
Resolves #1561.
> fix: downgrade AnyModel error to a warning (#1561)

- docs/integration.md
This PR polishes the integration docs.
> docs: update integration docs links

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/Pydantic.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
- fixes multi-line descriptions for the Pydantic preset in Python
Fixes #1058
> fix: multi line descriptions for the pydantic preset in python

- package-lock.json
- package.json
- src/processors/AsyncAPIInputProcessor.ts
This prepares modelina to be able to handle multiple parser versions. At some point in the future, I will update the underlying parser API we use to v2 instead of v1, so we automatically support v3.
I am marking this as a breaking change, ONLY because there might be edge cases, however, as you see I did not change any tests and still they pass.
Fixes https://github.com/asyncapi/modelina/issues/1493
> feat!: convert to use multi parser

- docs/migrations/version-2-to-3.md
- jest.config.js
- src/generators/java/JavaConstrainer.ts
- test/generators/java/JavaConstrainer.spec.ts
- This PR adds support for https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html
> feat!: adds support for duration in java

- jest.config.js
- package-lock.json
- package.json
- src/processors/AsyncAPIInputProcessor.ts
- test/processors/AsyncAPIInputProcessor.spec.ts
- test/processors/AsyncAPIInputProcessor/basic_v3.json
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
This PR enables v3 generation.
Fixes #1376
> feat: enable AsyncAPI v3

- docs/migrations/version-2-to-3.md
- examples/generate-csharp-models/__snapshots__/index.spec.ts.snap
- examples/generate-csharp-models/index.ts
- examples/generate-csharp-models/package-lock.json
- src/generators/csharp/CSharpConstrainer.ts
- test/blackbox/docs/AsyncAPI-2_6/dummy.json
- test/generators/csharp/CSharpConstrainer.spec.ts
Extending supported string formats for C#:
- format: 'date-time' will be rendered as DateTime in C#
- format: 'time' will be rendered as TimeStamp in C#
- format: 'uuid' will be rendered as Guid in C#
Added relevant tests and extended existing examples where relevant
Resolves #1607
> fix!: add csharp support for DateTime, TimeSpan, Guid

- docs/migrations/version-2-to-3.md
- src/helpers/CommonModelToMetaModel.ts
- src/helpers/ConstrainHelpers.ts
- src/helpers/Splitter.ts
- src/interpreter/InterpretAllOf.ts
- src/interpreter/Interpreter.ts
- src/models/CommonModel.ts
- src/models/ConstrainedMetaModel.ts
- src/models/MetaModel.ts
- test/helpers/CommonModelToMetaModel.spec.ts
- test/helpers/ConstrainHelpers.spec.ts
- test/helpers/Splitter.spec.ts
- test/interpreter/unit/InterpretAllOf.spec.ts
- test/interpreter/unit/Interpreter.spec.ts
- test/models/CommonModel.spec.ts
This is a preparation for adding inheritance with interfaces for Java in https://github.com/asyncapi/modelina/pull/1593
This PR finalizes what has been started regarding the `allowInheritance` option, and adds `extend` in the CommonModel, MetaModel, and ConstrainedMetaModel. It also adds logic in the Splitter to split our extended models and set `isExtended` in the options where this is needed.
See also https://github.com/asyncapi/modelina/issues/108.
> feat!: adds extend in common, meta, and constrained models

- docs/migrations/version-2-to-3.md
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/Pydantic.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
See https://www.blog.pythonlibrary.org/2021/09/11/python-3-10-simplifies-unions-in-type-annotations/
To be able to support Python pre 3.10, we need to adjust how types are rendered for union types. 
> feat!: render python union in pydantic in the pre 3.10 way

- modelina-website/src/components/Select.tsx
- modelina-website/src/components/docs/Docs.tsx
- modelina-website/src/components/examples/Examples.tsx
- modelina-website/src/components/playground/GeneratedModels.tsx
- modelina-website/src/components/playground/PlaygroundOptions.tsx
- modelina-website/src/components/playground/options/CSharpGeneratorOptions.tsx
- modelina-website/src/components/playground/options/CplusplusGeneratorOptions.tsx
- modelina-website/src/components/playground/options/DartGeneratorOptions.tsx
- modelina-website/src/components/playground/options/GeneralOptions.tsx
- modelina-website/src/components/playground/options/GoGeneratorOptions.tsx
- modelina-website/src/components/playground/options/JavaGeneratorOptions.tsx
- modelina-website/src/components/playground/options/JavaScriptGeneratorOptions.tsx
- modelina-website/src/components/playground/options/KotlinGeneratorOptions.tsx
- modelina-website/src/components/playground/options/PhpGeneratorOptions.tsx
- modelina-website/src/components/playground/options/PythonGeneratorOptions.tsx
- modelina-website/src/components/playground/options/RustGeneratorOptions.tsx
- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- modelina-website/src/pages/index.tsx
The current codebase of the Playground Generator Options, Docs, and Examples Components of the Modelina Website contained class-based react components. I have updated the code base to use functional components and hooks at all places. This results in cleaner, easier-to-understand components compared to class components.
Fixes #1648 
**Note**
This PR is to replace PR #1649 which just got destroyed by Pull bot.
> refactor(website): rewrite class-based functional components

- docs/constraints/Python.md
- docs/constraints/README.md
This PR adds documentation for explaining the constraint rules in python
Fixes #1674
> docs: add python constraint docs

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
In pydantic based python generator, when the optional values are passed, they need to be passed with an `default=None` argument in Field().
Fixes #1644
> fix: set default to None for pydantic generator

- docs/champions.md
This pull request addresses the issue [#1701]: "Emojis Not Rendering Properly in Hosted GitHub Documentation." The problem was related to inconsistencies in emoji rendering when the documentation is hosted on a website.
fixes https://github.com/asyncapi/modelina/issues/1701
- Updated the shortcut emojis to animated ones to resolve the rendering issue.
> docs: update Emojis Not Rendering Properly

- README.md
- docs/README.md
- docs/advanced.md
- docs/constraints/README.md
- docs/languages/Cplusplus.md
- docs/languages/Csharp.md
- docs/languages/Go.md
- docs/languages/Kotlin.md
- docs/languages/Php.md
- docs/languages/Scala.md
- docs/usage.md
- modelina-website/scripts/build-docs.js
This PR fixes a bunch of docs issues.
- Fixed Scala link to example
- Update list for data transfer presets
- Update constraint list
- Add missing example link
- Fix headlines for C++
- Add link to OpenAPI example in root readme
- Fix incorrect FAQ statement for C#
- Add missing Go language page
- Small fixes to Kotlin language page
- Fix website doc build script not giving integration page correct links when linking to integration examples
- Other small fixes.
> docs: bundle of small changes

- docs/migrations/version-2-to-3.md
- examples/README.md
- examples/typescript-use-esm/__snapshots__/index.spec.ts.snap
- examples/typescript-use-esm/index.spec.ts
- examples/typescript-use-js-reserved-keyword/README.md
- examples/typescript-use-js-reserved-keyword/__snapshots__/index.spec.ts.snap
- examples/typescript-use-js-reserved-keyword/index.spec.ts
- examples/typescript-use-js-reserved-keyword/index.ts
- examples/typescript-use-js-reserved-keyword/package-lock.json
- examples/typescript-use-js-reserved-keyword/package.json
- src/generators/typescript/Constants.ts
- src/generators/typescript/TypeScriptGenerator.ts
- src/generators/typescript/constrainer/EnumConstrainer.ts
- src/generators/typescript/constrainer/ModelNameConstrainer.ts
- src/generators/typescript/constrainer/PropertyKeyConstrainer.ts
- test/generators/typescript/constrainer/ModelNameConstrainer.spec.ts
Right now by default, we include JS keywords when checking for whether TS enum keys, properties, or model names can be a certain word. However, in most cases, people probably don't transpile their models into JS and so do not need that functionality. 
Introducing this option `useJavascriptReservedKeywords` makes it optional for people to include the list or not.
Fixes https://github.com/asyncapi/modelina/issues/1206
Fixes https://github.com/asyncapi/modelina/issues/1053
> feat!: add useJavascriptReservedKeywords option for TS

- modelina-website/src/pages/index.tsx
This PR is to redesign the hero of the website as discussed in issue #1293.
> style(website): redesign homepage

- package-lock.json
- package.json
- src/processors/JsonSchemaInputProcessor.ts
- test/processors/JsonSchemaInputProcessor.spec.ts
There was a problem where references were resolved regardless of where in the JSON Schema input they were located, meaning examples could NOT contain incorrect references. This PR fixes that as well as updating the reference handling library to the newest version.
> fix: edge case where references was incorrect handled for JSON Schema

- src/generators/typescript/TypeScriptConstrainer.ts
- src/models/ConstrainedMetaModel.ts
- src/utils/Partials.ts
- test/models/ConstrainedMetaModel.spec.ts
- test/utils/Partials.spec.ts
This PR fixes a problem where `getNearestDependencies` could not handle circular dependencies. 
I had to fix a few other problems as well:
- Fixed a problem with `partials` where the default value is returned as is instead of returning a new instance.
Fixes https://github.com/asyncapi/modelina/issues/1479
> fix: recursion bug for get nearest dependencies

- modelina-website/src/components/contexts/PlaygroundContext.tsx
- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/options/TypeScriptGeneratorOptions.tsx
- modelina-website/src/helpers/GeneratorCode/TypeScriptGenerator.ts
- modelina-website/src/pages/api/functions/TypeScriptGenerator.ts
- modelina-website/src/types/index.ts
Add TypeScript option for `mapType` to the playground.
Fixes #1756 
@jonaslagoni
> chore(website): add typescript map type option to the playground

- examples/adapting-input-and-output/__snapshots__/index.spec.ts.snap
- examples/csharp-auto-implemented-properties/__snapshots__/index.spec.ts.snap
- examples/csharp-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-equals-and-hashcode/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-handle-nullable/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-records/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-required-properties/__snapshots__/index.spec.ts.snap
- examples/generate-csharp-models/__snapshots__/index.spec.ts.snap
- src/generators/csharp/renderers/ClassRenderer.ts
- src/generators/csharp/renderers/RecordRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/CommonPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
Adds `partial` modifier to generated types.
* Partial types in C#: https://github.com/asyncapi/modelina/issues/1776
I don't think any documentation changes are required?
> feat: ensure C# types are generated with 'partial' modifier.

- src/models/ConstrainedMetaModel.ts
- src/utils/Partials.ts
This PR fixes the implementation for partial that incorrectly handles array values, and thereby fixing the playground and others that dependent on Modelina.
The problem arose when the array values contained instances of classes that would be re-created incorrectly. We only intend to merge the default and target together.
> fix: partial and playground

- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/runtime/generic-input.json
- test/runtime/runtime-csharp/runtime-csharp/test/models/json_serializer/Address.cs
- test/runtime/runtime-csharp/runtime-csharp/test/models/newtonsoft/Address.cs
Ensures enums with a different name to the property are correctly serialized by `System.Text.Json`. 
Fixes #1783 
No documentation change required
> fix: incorrect enum serializer generation for System.Text.Json

- docs/migrations/version-3-to-4.md
- src/helpers/FormatHelpers.ts
- test/generators/typescript/constrainer/PropertyKeyConstrainer.spec.ts
The `toCamelCase` helper produced wrong outputs in some edge cases, where there was a numeric followed by "_" and a lowercase letter. This PR aims to fix that.
Fixes #1503
> fix!: handle edge case in toCamelCase FormatHelper

- modelina-website/scripts/build-docs.js
The import directory in 'build-docs.js' did not match the one set in package.json (`"copy:docs:img": "cp -r ../docs/img public/img/docs"`)
Fixes #1700
> chore(website): wrong import directory for docs images

- src/generators/typescript/presets/utils/UnmarshalFunction.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
There seems to be a bug introduced in https://github.com/asyncapi/modelina/pull/1717/files. Properties that have `const` set are read-only, and can't be set when unmarshaling. If this is not fixed, then the TS compiler fails on the generated code.
> fix: dont render unmarshal for property with const

- src/generators/typescript/presets/DescriptionPreset.ts
- test/generators/typescript/preset/__snapshots__/DescriptionPreset.spec.ts.snap
This pull request corrects the generated code docs to their expected position.
| Earlier | Now |
| --- | --- |
| ![Screenshot-1](https://github.com/asyncapi/modelina/assets/96991785/148c9d75-45f5-4214-a74d-7f32e29b2f39)|![Screenshot-2](https://github.com/asyncapi/modelina/assets/96991785/b8e2dbae-227a-4389-a7b3-a77981bc395f)|
Fixes #1548
> fix: generate doc for getters

- docs/migrations/version-3-to-4.md
- src/generators/csharp/constrainer/ConstantConstrainer.ts
- src/generators/csharp/presets/JsonSerializerPreset.ts
- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
- src/generators/csharp/renderers/ClassRenderer.ts
- src/generators/csharp/renderers/RecordRenderer.ts
- test/generators/csharp/CSharpGenerator.spec.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/csharp/presets/JsonSerializerPreset.spec.ts
- test/generators/csharp/presets/NewtonsoftSerializerPreset.spec.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
Enable the C# Class and Record Generators to properly handle constant values.
fixes #1471
> feat!: properly implement constants in c#

- docs/languages/Python.md
This PR updates the link in the python docs to the preset, no need to link to the code.
> docs: update link in Python docs

- src/generators/python/PythonGenerator.ts
Correctly type the dependencyManager option for the PythonGenerator
Fixes #1810
> fix: python generator type safety

- docs/migrations/version-3-to-4.md
- examples/generate-csharp-models/__snapshots__/index.spec.ts.snap
- src/generators/csharp/CSharpConstrainer.ts
- test/generators/csharp/CSharpConstrainer.spec.ts
There was a problem in the recent addition of mapping for `date` and `date-time` field to C#.
Following AsyncAPI documentation:
And the RFC documentation:
My simple change rectify this situation.
> fix!: mapping for C# object date

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This PR adds serialization alias field tags for the Pydantic preset, so properties are accurately serialized and deserialized
> fix: add serialization alias for Pydantic 

- docs/languages/Python.md
- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This PR adds the exclusion tag for properties with type `ConstrainedDictionaryModel` with `serialilzationType = unwrap` to make sure they don't clutter up the serialized JSON.
Blocked by #1859 (this extends it)
> fix: exclude unwrappable dictionaries for pydantic preset

- docs/presets.md
- examples/generate-go-enums/__snapshots__/index.spec.ts.snap
- src/generators/go/GoPreset.ts
- src/generators/go/renderers/EnumRenderer.ts
- test/generators/go/GoGenerator.spec.ts
- test/generators/go/__snapshots__/GoGenerator.spec.ts.snap
This PR fixes multiple bugs with the Go enum rendering, where only the `self` hook was called. Now both `item` and `additionalContent` are called.
Fixes https://github.com/asyncapi/modelina/issues/1847
> fix: only self hook was called in Go enums

- docs/migrations/version-3-to-4.md
- examples/generate-python-complete-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- examples/python-generate-json-serializer-and-deserializer/__snapshots__/index.spec.ts.snap
- src/generators/python/constrainer/ModelNameConstrainer.ts
- src/generators/python/constrainer/PropertyKeyConstrainer.ts
- src/generators/python/presets/JsonSerializer.ts
- test/generators/python/__snapshots__/PythonGenerator.spec.ts.snap
- test/generators/python/constrainer/EnumConstrainer.spec.ts
- test/generators/python/constrainer/ModelNameConstrainer.spec.ts
- test/generators/python/constrainer/PropertyKeyConstrainer.spec.ts
- test/generators/python/presets/__snapshots__/JsonSerializer.spec.ts.snap
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This PR uses the standard style guide for properties and model names:
- Variables and functions: https://peps.python.org/pep-0008/#function-and-variable-names
- Model names: https://peps.python.org/pep-0008/#class-names
Fixes https://github.com/asyncapi/modelina/issues/1818
> fix!: use recommended Python styles for names

- examples/csharp-change-collection-type/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-equals-and-hashcode/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap
- examples/csharp-generate-required-properties/__snapshots__/index.spec.ts.snap
- examples/csharp-use-inheritance/__snapshots__/index.spec.ts.snap
- examples/generate-csharp-models/__snapshots__/index.spec.ts.snap
- src/generators/csharp/renderers/ClassRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/CommonPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
The setter for c# class properties should use this.{propertyName} to assign values to avoid an edge case where there is a property named 'value'
Fixes #1862
> fix: use this. for property setter in c# class renderer

- docs/migrations/version-3-to-4.md
- docs/presets.md
- examples/README.md
- examples/json-schema-single-enum-as-const/README.md
- examples/json-schema-single-enum-as-const/__snapshots__/index.spec.ts.snap
- examples/json-schema-single-enum-as-const/index.spec.ts
- examples/json-schema-single-enum-as-const/index.ts
- examples/json-schema-single-enum-as-const/package-lock.json
- examples/json-schema-single-enum-as-const/package.json
- src/helpers/CommonModelToMetaModel.ts
- src/models/ProcessorOptions.ts
- src/processors/AsyncAPIInputProcessor.ts
- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- src/processors/SwaggerInputProcessor.ts
- src/processors/TypeScriptInputProcessor.ts
- test/generators/java/presets/DescriptionPreset.spec.ts
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/helpers/CommonModelToMetaModel.spec.ts
- test/processors/SwaggerInputProcessor.spec.ts
- test/processors/__snapshots__/OpenAPIInputProcessor.spec.ts.snap
- test/processors/__snapshots__/SwaggerInputProcessor.spec.ts.snap
- test/processors/__snapshots__/TypeScriptInputProcessor.spec.ts.snap
This PR enables single enum values to be interpreted as a constant instead of creating a separate enum class in most cases.
Fixes https://github.com/asyncapi/modelina/issues/1827
> feat: allow change of how enum is interpreted when a single value 

- examples/generate-python-complete-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-models/__snapshots__/index.spec.ts.snap
- examples/python-generate-json-serializer-and-deserializer/__snapshots__/index.spec.ts.snap
- src/generators/python/renderers/ClassRenderer.ts
- src/generators/python/renderers/EnumRenderer.ts
- src/helpers/FormatHelpers.ts
- test/generators/python/__snapshots__/PythonGenerator.spec.ts.snap
- test/generators/python/presets/__snapshots__/JsonSerializer.spec.ts.snap
This PR fixes the inconsistent indentation for the Python models where explicit `\t` characters where used.
Fixes https://github.com/asyncapi/modelina/issues/1817
> fix: inconsistent indentation for Python models

- src/generators/python/PythonConstrainer.ts
- test/generators/python/PythonConstrainer.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This PR fixes that the Python constrainer is using an incorrect value for the key for dictionaries.
> fix: python using the wrong key type for dictionaries

- docs/migrations/version-3-to-4.md
- src/generators/go/GoFileGenerator.ts
- test/generators/FileGenerators.spec.ts
- test/generators/__snapshots__/FileGenerators.spec.ts.snap
This MR enforces go file names to be in snake_case format. This is considered best practice in golang: https://github.com/golang/go/issues/36060
> feat!: use snake case for file names in go

- test/generators/FileGenerators.spec.ts
- test/generators/__snapshots__/FileGenerators.spec.ts.snap
https://github.com/asyncapi/modelina/actions/runs/8279349802/job/22653559947 failed because the path is different in windows. Should be fixed now
> fix!: fixes tests for windows

- examples/README.md
- examples/json-schema-additional-properties-representation/README.md
- examples/json-schema-additional-properties-representation/__snapshots__/index.spec.ts.snap
- examples/json-schema-additional-properties-representation/index.spec.ts
- examples/json-schema-additional-properties-representation/index.ts
- examples/json-schema-additional-properties-representation/package-lock.json
- examples/json-schema-additional-properties-representation/package.json
- examples/json-schema-single-enum-as-const/__snapshots__/index.spec.ts.snap
- examples/json-schema-single-enum-as-const/index.spec.ts
- src/helpers/CommonModelToMetaModel.ts
- src/processors/JsonSchemaInputProcessor.ts
This PR enables customization of what represents additional properties in an ObjectModel.
Fixes https://github.com/asyncapi/modelina/issues/1879
> feat: enable customization of additional property represenation

- .github/workflows/upload-release-assets.yml
Currently the CLI binaries are not uploaded on `next`, this fixes that
> feat: trigger upload resources on next

- .github/workflows/upload-release-assets.yml
- modelina-cli/scripts/releasePackagesRename.js
This PR fixes the Cli CI packing pipeline where the directories are not created correctly as seen here: https://github.com/asyncapi/modelina/actions/runs/8537797869
This PR also re-triggers the release pipeline and releases a new version to check whether it works.
Related to https://github.com/oclif/oclif/pull/1322
> feat: fix Cli CI packaging pipeline

- src/processors/JsonSchemaInputProcessor.ts
- src/processors/OpenAPIInputProcessor.ts
- src/processors/SwaggerInputProcessor.ts
- test/processors/JsonSchemaInputProcessor.spec.ts
- test/processors/OpenAPIInputProcessor.spec.ts
- test/processors/OpenAPIInputProcessor/references_circular.json
- test/processors/SwaggerInputProcessor.spec.ts
- test/processors/SwaggerInputProcessor/references_circular.json
- test/processors/__snapshots__/OpenAPIInputProcessor.spec.ts.snap
- test/processors/__snapshots__/SwaggerInputProcessor.spec.ts.snap
Generating models for OpenAPI 3 and Swagger documents fail due to infinite recursion in `JsonSchemaInpoutProcessor:reflectSchmaNames(...)` if the schema uses `$ref` that result in cycles in the schema.
Example failure message:
```text
Generating models from: /openapi.yaml
.../node_modules/@asyncapi/modelina/lib/cjs/processors/JsonSchemaInputProcessor.js:197
static reflectSchemaNames(schema, namesStack, name, isRoot) {
RangeError: Maximum call stack size exceeded
at JsonSchemaInputProcessor.reflectSchemaNames (.../node_modules/@asyncapi/modelina/lib/cjs/processors/JsonSchemaInputProcessor.js:197:30)
at JsonSchemaInputProcessor.reflectSchemaNames (.../node_modules/@asyncapi/modelina/lib/cjs/processors/JsonSchemaInputProcessor.js:245:37)
at JsonSchemaInputProcessor.reflectSchemaNames …
```
> fix: circular schema issue with OpenAPI, JSON Schema, and swagger inputs

- .github/workflows/upload-release-assets.yml
This PR disables fail fast so even if one packaging fails, the rest continues to work fine.
> ci: switch to fail slow for Cli release

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-pydantic-models/index.ts
- src/generators/python/constrainer/PropertyKeyConstrainer.ts
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This enables the generated models for Pydantic to work for properties with dashes in the name.
The generated code now puts descriptions in the "description" argument of the Pydantic Field decorator, and puts the original, unconstrained, property name in the "alias" field. This is correct usage as per the [Pydantic documentation](https://docs.pydantic.dev/latest/concepts/fields/#field-aliases)
Also, dashes are allowed through in property key constrainer, so that a property name like "content-type" is converted into "contentType" instead of "contentMinusType".
I believe this fixes https://github.com/asyncapi/modelina/issues/1058 but apparently that has been closed with a fix to an mostly unrelated problem.
With these changes the generated Pydantic model class can correctly deserialise and …
> fix: support dash in property names (Pydantic generator)

- src/generators/java/JavaConstrainer.ts
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/presets/CommonPreset.spec.ts
This PR fixes that Java does not import the right dependencies when specific types are used.
Fixes https://github.com/asyncapi/modelina/issues/1892
> fix: java does not import correct types

- docs/languages/Go.md
This PR updates the go language docs to better explain that JSON tags are supported.
> docs: update go language docs

- examples/integrate-with-maven/maven-project/pom.xml
- examples/integrate-with-maven/maven-project/scripts/modelina/generate.ts
- examples/integrate-with-maven/maven-project/scripts/modelina/package.json
* Make the npm script portable in Maven example. npm guideline is to not prefix with relative path, as executables are added to the $PATH. Tested on Windows and macOS.
* Add missing "npm install" excution to Maven frontend plugin.
I don't think it's applicable, as the examples are not run in the CI ?
> chore: make the npm script portable in Maven example

- docs/languages/Python.md
- docs/migrations/version-3-to-4.md
- examples/generate-python-complete-models/__snapshots__/index.spec.ts.snap
- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/PythonConstrainer.ts
- src/generators/python/PythonDependencyManager.ts
- src/generators/python/PythonGenerator.ts
- src/generators/python/presets/Pydantic.ts
- src/generators/python/renderers/ClassRenderer.ts
- src/helpers/CommonModelToMetaModel.ts
- test/generators/python/PythonConstrainer.spec.ts
- test/generators/python/PythonDependencyManager.spec.ts
- test/generators/python/PythonGenerator.spec.ts
- test/generators/python/__snapshots__/PythonGenerator.spec.ts.snap
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
This PR fixes two major problems with the Python generator; self-referencing models give errors and circular model dependencies do not work.
If a model depends on itself the current dependency setup will not work in Python. This fixes it by changing the import style to using forward references (`forward references: when a type hint contains names that have not been defined yet, that definition needs to be expressed as a string literal;`) through the new [Postponed Evaluation of Annotations](https://peps.python.org/pep-0563/).
I tried to experiment with all kinds of different solutions, such as those highlighted here: https://stackoverflow.com/a/55344418/6803886
However, this one was the most straightforward solution. It does mean that we add the requirement of using at least Python 3.7, …
> fix!: python models not handling circular model dependencies

- docs/migrations/version-3-to-4.md
- src/generators/go/renderers/StructRenderer.ts
- src/generators/go/renderers/UnionRenderer.ts
- test/generators/go/GoGenerator.spec.ts
- test/generators/go/__snapshots__/GoGenerator.spec.ts.snap
I got some feedback after https://github.com/asyncapi/modelina/pull/1958 was merged. This fixes some issues with the union type with discriminator in go.
> fix: fixes union type with discriminator in go

- .github/workflows/if-nodejs-release.yml
As long as https://github.com/asyncapi/.github/pull/294 is not merged, this patch is needed
> ci: make sure release workflow works in next

- src/helpers/CommonModelToMetaModel.ts
refactor: Adding modelName to the warning log.
refactor: Added modelName to the warning log to explicitly mention the model in the logs which is running into a warning state while generating models
- [ ✅  ] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [ ✅  ] Tests have been added or updated to cover the changes.
- [ ✅  ] Documentation has been updated to reflect the changes.
- [ ✅ ] All tests pass successfully locally.(`npm run test`).
> feat: add modelName to warning log

- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/Pydantic.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
Add a test for a required, but nullable, union type and update the Pydantic preset to treat nullable properties as optional.
Fixes https://github.com/asyncapi/modelina/issues/2000
> fix: treat nullable property as optional

- modelina-cli/src/helpers/typescript.ts
- modelina-cli/test/integration/generate.test.ts
This PR adds support for using the `--tsRawPropertyNames` that was introduced in https://github.com/asyncapi/cli/pull/1362
> feat: add typescript raw option to the CLI 

- examples/go-json-tags/__snapshots__/index.spec.ts.snap
- src/generators/go/presets/CommonPreset.ts
- test/generators/go/presets/__snapshots__/CommonPreset.spec.ts.snap
Had an extra space which was causing problem and was not working.
> fix: bug with omitempty tag

- modelina-cli/README.md
- modelina-cli/src/helpers/java.ts
- modelina-cli/test/integration/generate.test.ts
This PR adds support to change the collection type in Java models by introducing a new parameter "javaArrayType" to the generate models command.
> feat: adding support to change the collection type for arrays in Java models

- src/generators/index.ts
Add an export statement for AbstractDependencyManager in the index.ts file.
Fixes https://github.com/asyncapi/modelina/issues/2005
> feat: export AbstractDependencyManager to allow override

- examples/go-union-type/__snapshots__/index.spec.ts.snap
- src/generators/go/presets/CommonPreset.ts
- src/generators/go/renderers/UnionRenderer.ts
- test/generators/go/__snapshots__/GoGenerator.spec.ts.snap
Adding `json` tags on go union types, to omit if empty. 
Fixes #2034
> feat: json tag support for go union

- src/generators/csharp/CSharpConstrainer.ts
- test/generators/csharp/CSharpConstrainer.spec.ts
Added extra constraints for integer types in the C# generator so int64 format results in long types.
Fixes https://github.com/asyncapi/modelina/issues/2053
> feat!: expand format for integer types for C#

- modelina-cli/src/helpers/python.ts
- modelina-cli/test/integration/generate.test.ts
Add an option to the modelina CLI to enable the PYDANTIC preset for Python output.
> feat: add --pyDantic to cli for Python and Pydantic preset

- modelina-website/package-lock.json
- modelina-website/package.json
- modelina-website/src/components/MonacoEditorWrapper.tsx
- modelina-website/src/components/contexts/PlaygroundContext.tsx
- modelina-website/src/components/playground/Content.tsx
- modelina-website/src/components/playground/Playground.tsx
- modelina-website/src/components/playground/Sidebar.tsx
- modelina-website/src/pages/playground.tsx
- modelina-website/tailwind.config.js
- User be able to choose between input editor or output editor
- When opening general options or generator options it will close others, work back and forth
- On Mobile devices when opening the general option it will take the full display area, and the active button will indicate it's open
- Refactor the code from using `Flex `to `Grid` which reduces multiple unnecessary div components and enables us to keep the existing desktop design
- Change the first implementation from conditional rendering to using CSS hidden property, so the bug we encounter not become relevant anymore and we remove the quick fix we implemented before
- I decided to add more space on the input editor and take it from output result in bigger device notebook/desktop because of user probably will work more on the the …
> style(website): make Playground Mobile Responsive

- examples/go-union-type/__snapshots__/index.spec.ts.snap
- src/generators/go/presets/CommonPreset.ts
- src/generators/go/renderers/UnionRenderer.ts
- test/generators/go/__snapshots__/GoGenerator.spec.ts.snap
Added missing FieldType in go union renderer```return `${options.unionArrModelName} ${fieldType}`; ```
> fix: add missing fieldtypes for go union types 

- modelina-website/src/components/layouts/Head.tsx
Images in HeadComponents is not the actual folder where the images have been put in
Fixes #1165
> fix(website): fix broken open graph images

- docs/migrations/version-3-to-4.md
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
In Java, when a class implements an interface, it must implement all the methods of that interface. Because of that, Modelina now doesn't render the setter for enums in interfaces when `allowInheritance` is true because the classes that implement the interface might use a constant value.
> feat!: no setters for enums in interfaces for java when allowInheritance is used

- README.md
This changes the readme to showcase that v3 is supported
> docs: add asyncapi v3 support in readme

- examples/java-generate-jakarta-constraint-annotation/README.md
- examples/java-generate-jakarta-constraint-annotation/__snapshots__/index.spec.ts.snap
- examples/java-generate-jakarta-constraint-annotation/index.spec.ts
- examples/java-generate-jakarta-constraint-annotation/index.ts
- examples/java-generate-jakarta-constraint-annotation/package-lock.json
- examples/java-generate-jakarta-constraint-annotation/package.json
- examples/kotlin-generate-jakarta-constraint-annotation/README.md
- examples/kotlin-generate-jakarta-constraint-annotation/__snapshots__/index.spec.ts.snap
- examples/kotlin-generate-jakarta-constraint-annotation/index.spec.ts
- examples/kotlin-generate-jakarta-constraint-annotation/index.ts
- examples/kotlin-generate-jakarta-constraint-annotation/package-lock.json
- examples/kotlin-generate-jakarta-constraint-annotation/package.json
- src/generators/java/presets/ConstraintsPreset.ts
- src/generators/kotlin/presets/ConstraintsPreset.ts
- test/generators/java/presets/ConstraintsPreset.spec.ts
- test/generators/java/presets/__snapshots__/ConstraintsPreset.spec.ts.snap
- test/generators/kotlin/presets/ConstraintsPreset.spec.ts
- test/generators/kotlin/presets/__snapshots__/ConstraintsPreset.spec.ts.snap
feat: Allow to use constraints from jakarta namespace for Java and Kotlin models
The JAVA_CONSTRAINT_PRESET uses constraints from the javax namespace. 
Since Java 17 the constraints are moved to the jakarta namespace. Add an options to the JAVA_CONSTRAINT_PRESET to use the jakarta namespace for constraint imports.
fixes: #1807
Nothing to add from my side.
> feat: allow to use constraints from jakarta namespace for Java and Kotlin models

- package-lock.json
- package.json
- src/processors/AsyncAPIInputProcessor.ts
[@smoya/multi-parser](https://github.com/smoya/multi-parser-js) has been deprecated. Now its source code is included and released as part of https://github.com/asyncapi/parser-js monorepo.
> chore: use @asyncapi/multi-parser instead of @smoya/multi-parser

- src/generators/csharp/renderers/EnumRenderer.ts
Changed parameter type of ToEnum extension methods to dynamic.
fixes https://github.com/asyncapi/modelina/issues/2063
> fix: make parameter type of ToEnum extension methods dynamic

- examples/csharp-overwrite-enum-naming/__snapshots__/index.spec.ts.snap
- src/generators/csharp/renderers/EnumRenderer.ts
- test/generators/csharp/__snapshots__/CSharpGenerator.spec.ts.snap
Fixes https://github.com/asyncapi/modelina/issues/2063
> fix: make parameter type of ToEnum extension methods dynamic (#2064)

- docs/migrations/version-3-to-4.md
- src/generators/AbstractGenerator.ts
- src/generators/java/renderers/ClassRenderer.ts
- src/models/ConstrainedMetaModel.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
#2068 introduced some breaking changes for the Java code that Java users didn't like. They want setters when they can exist, and this fixes that.
In Java, when a class implements an interface, it must implement all the methods of that interface. Therefore, if `allowInheritance` is set to true, Modelina will no longer render the setter for enums in interfaces if the property exists in the implemented by class with a constant value.
Fixes #2068
> fix!: when allowInheritance is true, java now renders setters in interfaces for enums if const is not set by the classes that implements it

- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
#2096 introduced a compile error bug in some cases, and this PR fixes that.
Fixes #2096
> fix!: dont render override when the setter doesnt exist in the interface

- examples/java-generate-jackson-annotation/__snapshots__/index.spec.ts.snap
- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
* Adds @JsonAnySetter and @JsonAnyGetter annotations to additionalProperties
Adds these annotations so that Jackson can marshall and unmarshall additional properties.
> feat!: add jackson annotations additionalProperties

- modelina-website/src/helpers/GeneratorCode/KotlinGenerator.ts
When using showTypeMappingExample in the Kotlin generator, the example code includes a import keyword in the dependency string which causes the generated code to have an invalid double import statement.
fixes https://github.com/asyncapi/modelina/issues/2107
- [✅] The code follows the project's coding standards and is properly linted (`npm run lint`).
- [✅] All tests pass successfully locally.(`npm run test`).
> fix: remove duplicate import keyword in Kotlin generator example

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
1. Pydantic code generation now checks if data is a dict or an object before getting keys in the unwrap functions.
2. Alias has been removed for unconstrained properties so that Pydantic objects can follow idiomatic casing for the additional_properties property:
```python
MyPydanticObject(
defined_property=1,
additional_properties={
"undefined_property": "2"
}
)
```
> fix: python pydantic unwrap properties

- src/generators/typescript/presets/utils/UnmarshalFunction.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
This PR adds support for properly unmarshalling array types, when using the TypeScript generator. Previously, the JSON array was being passed straight into the resulting object, which causes issues when using the value in another schema object and marshalling that object. The other object expects the array to contain full objects with a callable `marshal` function, not a plain object, giving an error like:
```
err: {
"type": "TypeError",
"message": "unionItem.marshal is not a function",
"stack":
TypeError: unionItem.marshal is not a function
at KeywordSearchRequest.marshal
...
```
Given a type like this:
```yaml
arrayProperty:
type: array
items:
$ref: "#/definitions/SomeObjectType"
```
The generator will now generate unmarshalling code like this:
```typescript
...
instance.arrayProperty = …
```
> feat: add support for typed array unmarshalling in TypeScript

- src/generators/typescript/presets/utils/UnmarshalFunction.ts
- test/generators/typescript/preset/MarshallingPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/MarshallingPreset.spec.ts.snap
There's currently a bug on 3.10.0 where calls to unmarshal are made on arrays of primitive type. Here's an example of the generated code:
This PR prevents the issue by adding new checks.
N/A
By the way, noticed that version 4.0.0 doesn't include unmarshalling array items, and that might be an issue (at least for my use cases). Just letting you know so you can keep track of this, in case it's not expected.
> fix: preventing unmarshal on primitive types

- examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/NewtonsoftSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/NewtonsoftSerializerPreset.spec.ts.snap
This PR updates next with master
> feat: update with master

- examples/java-generate-jakarta-constraint-annotation/__snapshots__/index.spec.ts.snap
- examples/java-generate-javax-constraint-annotation/__snapshots__/index.spec.ts.snap
- src/generators/java/presets/ConstraintsPreset.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/ConstraintsPreset.spec.ts.snap
- Add missing `@Valid` annotations
- Update tests
#2175
> fix: the Java Constraint Generator omits `@Valid` annotation

- src/generators/java/presets/ConstraintsPreset.ts
- test/generators/java/presets/ConstraintsPreset.spec.ts
- Add missing annotation
- Update tests
#2175
Sorry, just noticed that I have missed to add the import in #2176 (made with my work account).
> fix: add missing Java import for `@Valid` annotation

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
@jonaslagoni not sure if you're the original author - could you review this? See #2174 
Fixes #2174
> fix: remove double None from Pydantic preset

- src/helpers/CommonModelToMetaModel.ts
- test/generators/go/presets/DescriptionPreset.spec.ts
- test/generators/go/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/java/presets/DescriptionPreset.spec.ts
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/kotlin/presets/DescriptionPreset.spec.ts
- test/generators/kotlin/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/php/presets/DescriptionPreset.spec.ts
- test/generators/php/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/scala/presets/DescriptionPreset.spec.ts
- test/generators/scala/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/typescript/preset/DescriptionPreset.spec.ts
- test/generators/typescript/preset/__snapshots__/DescriptionPreset.spec.ts.snap
- test/processors/__snapshots__/AsyncAPIInputProcessor.spec.ts.snap
When a spec has a property that defines an open object like:
```
anyProp: {
type: 'object',
$id: 'AnyTest',
properties: {},
description: 'AnyTest description'
}
```
it does not add the description to the generated models.
This PR fixes this issue.
> fix: description preset for any types

- examples/java-generate-jackson-annotation/__snapshots__/index.spec.ts.snap
- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/JacksonPreset.spec.ts
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
Jackson handles poorly serialization of properties of names with first word length of 1 (such as `a_name`, `x_min`, `y_max`) when the `@JsonProperty` annotation is put on the field. Putting the annotation on the getter fixes this behavior while retaining the ability to deserialize and serialize properties with names defined by the `@JsonProperty` annotation.
example:
```java
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
public class Example {
@JsonProperty("a_property")
private Integer aProperty;
public Integer getAProperty() {
return aProperty;
}
public void setAProperty(Integer aProperty) {
this.aProperty = aProperty;
}
public static void main(String[] args) {
ObjectMapper mapper = new ObjectMapper();
Example example = new …
```
> fix: move jsonproperty annotation to getter

- src/generators/rust/RustConstrainer.ts
- test/generators/rust/RustConstrainer.spec.ts
I added all possible signed and unsigned types to the rust generator
Fixes https://github.com/asyncapi/modelina/issues/2208
> feat: add support for all rust number types

- examples/README.md
- examples/java-generate-records/README.md
- examples/java-generate-records/__snapshots__/index.spec.ts.snap
- examples/java-generate-records/index.spec.ts
- examples/java-generate-records/index.ts
- examples/java-generate-records/package-lock.json
- examples/java-generate-records/package.json
- src/generators/java/Constants.ts
- src/generators/java/JavaGenerator.ts
- src/generators/java/JavaPreset.ts
- src/generators/java/renderers/RecordRenderer.ts
Java equivalent of #1191. This PR adds an option to the Java generator allowing it to render records instead of classes. This is done using a new renderer that implements self, property and additionalContent hooks. 
Resolves #2218
> feat: add Java record support

- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
I ran into errors where the generated class's custom JsonConverter implementation was applying to objects that it should not be applying to. It applied the same JsonConverter to the properties of the object. For example, lets say we have a class called `Robot` and two properties (`name: string`, and `id: System.Guid`). If `CanConvert` always returns `true`, then when parsing a json string to the `Robot` class, it will use the `RobotConverter` on the `System.Guid` causing it to fail.
According to [Microsoft Documentation](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to):
```
Override the CanConvert method only if necessary.
The default implementation returns true when the type to convert is of type T.
Therefore, converters that support …
```
> fix(csharp-json-generator): remove CanConvert override for Json converters

- src/generators/java/JavaPreset.ts
- src/generators/java/renderers/UnionRenderer.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
This PR fixes issue https://github.com/asyncapi/modelina/issues/2230
**Another option is to remove the setter on the generated class using the union interface**
If you guys like that more, let me know and I will change it
> feat: add missing setter in union interface leading to compile errors in implementing classes

- src/generators/java/renderers/ClassRenderer.ts
- src/generators/java/renderers/UnionRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
This PR fixes issue: https://github.com/asyncapi/modelina/issues/2229
It was partially supported. The overriden getters on the subclasses where generated correct. But the getter on the union was generated in correctly due to no support for special chars. This lead to compile errors in the generated code.
> feat: add support for special characters in discriminator for java generator

- examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap
- src/generators/csharp/presets/JsonSerializerPreset.ts
- test/generators/csharp/presets/__snapshots__/JsonSerializerPreset.spec.ts.snap
I ran into issues where a json string fails to `Deserialize` if there are unknown properties in the json document.
This happens because when an unknown property is read, we do not move the reader forward to the next property token.
For example, `Address.cs`
```
public override Address Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options)
{
if (reader.TokenType != JsonTokenType.StartObject)
{
throw new JsonException();
}
var instance = new Address();
while (reader.Read())
{
if (reader.TokenType == JsonTokenType.EndObject)
{
return instance;
}
// Get the key.
if (reader.TokenType != JsonTokenType.PropertyName)
{
throw new JsonException();
}
string propertyName = reader.GetString();
if (propertyName == "id")
{
var value = …
```
> fix: gracefully handle unknown properties

- package-lock.json
- package.json
In one of our project we have a project where `tsconfig.json` option `skipLibCheck` is `false` _(disabled by default)_.
In this project our type check part of the CI is failing due to type issues inside the old version `openapi-types`, which is a direct dependency of `@asyncapi/modelina`.
This is the error we're getting:
```log
TS2344: Type 'T' does not satisfy the constraint '{}'.
16         paths: PathsObject<T>;
~
<redacted>/node_modules/openapi-types/dist/index.d.ts:15:34
15     type PathsWebhooksComponents<T> = {
~
This type parameter might need an `extends {}` constraint.
Found 1 error in <redacted>/node_modules/openapi-types/dist/index.d.ts:16
```
So, updating `openapi-types` would help us get rid of this problem.
> fix: update `openapi-types` to `^v12.1.3`

- src/generators/java/renderers/UnionRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
For Java modelType record when using unions (oneOf), the currently generated code doesn't compile.
It generates an interface with `String getMyDiscriminator();` while the record has an automatic getter with signature `String myDiscriminator()`.
In this PR we don't prefix discriminator getter with "get" in the union renderer.
/
The test uses asyncapi 3.0.0
> fix: records implement union interface for Java

- src/generators/java/renderers/ClassRenderer.ts
- src/generators/java/renderers/RecordRenderer.ts
Currently `java.util.List` is always imported if `collectionType` is set to `List`, even if no array properties exist in the model. This PR adds a check to ensure the model contains an array property, in addition to having `collectionType` set to `List`.
> fix: only import List if a list is present for Java

- examples/generate-all-models-within-the-same-file/__snapshots__/index.spec.ts.snap
- src/generators/java/renderers/EnumRenderer.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
- test/generators/java/presets/__snapshots__/DescriptionPreset.spec.ts.snap
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
In Java enum, the contained value cannot be changed and is best declared final.
/
/
> fix: mark property as final for Java 

- src/generators/java/JavaConstrainer.ts
- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
In java, when we have a List with uniqueItems we use a Set instead of a List, in this PR we add support for unique arrays which creates a Set instead of List
> feat: support unique arrays for Java

- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/Pydantic.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
Code generated for python with Pydantic is missing default values for discriminator field, when polymorphism is used with discriminator assigned via const. This PR adds `default` value to field and sets the field as `frozen`.
Resolves #2270 
---
> fix: missing default value in Pydantic generated code when using polymorphism

- modelina-cli/package-lock.json
- modelina-cli/package.json
Testing after `v5.2.1` release of #2771 showed, that fix is not there, when modelina-cli is used.
It truns out, that CLI was depending on previous major of modelina.
#2274
> fix: modelina-cli has wrong version of modelina as dependency

- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
#	examples/java-generate-optionals-for-non-required-fields/README.md
> fix: do not use optionals for non-required arrays in Java

- examples/generate-python-pydantic-models/__snapshots__/index.spec.ts.snap
- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/Pydantic.spec.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
#2111 removed aliases, which was a breaking (and perhaps unintended) change that broke the API and thus downstream consumers. This change adds auto aliasing back in.
fixes #2187
partially reverts PR #2111
tests on main are red atm; tests for the generator are green (existing + new)
> fix: add aliasing back in for Pydantic generator

- src/generators/python/presets/Pydantic.ts
- test/generators/python/presets/__snapshots__/Pydantic.spec.ts.snap
when doing deserialization in pydantic only unknown properties must be added to additional_properties
current generated code contains a bug, which leads to matched fields appearing in `additional_properties`.
the fix is pretty trivial and straight-forward: we only process unknown properties. 
it seemed to not worth creating one for such a trivial fix.
> fix: deserialization in pydantic

- src/generators/java/index.ts
Add export for the default constant constraint
None
Only adding some visibility to ease override of constrainers.
> fix: missing export for default constant contraint of java generator

- src/generators/java/presets/JacksonPreset.ts
- test/generators/java/presets/JacksonPreset.spec.ts
- test/generators/java/presets/__snapshots__/JacksonPreset.spec.ts.snap
Supports defining a default subtype in Jackson when using a union
> feat: support default jackson subtype for unions

- src/generators/java/renderers/ClassRenderer.ts
- test/generators/java/JavaGenerator.spec.ts
- test/generators/java/__snapshots__/JavaGenerator.spec.ts.snap
Test case and fix for Java generator, when a discriminator has a special character, e.g. `"@type"` and a default.
https://github.com/asyncapi/modelina/issues/2332
Fix to be implemented, test result to change from as-is to fixed.
> fix: discriminator with special character and default
